ansible-collections/ansible.windows

plugins/action/win_copy.py, plugins/action/win_template.py, plugins/action/win_updates.py, plugins/modules/win_copy.ps1, plugins/modules/win_template.py, tests/integration/targets/win_copy/tasks/remote_tests.yml, tests/integration/targets/win_copy/tasks/tests.yml, tests/integration/targets/win_template/tasks/main.yml
Change the action plugins to call the FQCN of the module it needs to execute so that when they are called without the `collections:` keyword it will work.
Also updates the behaviour of `win_copy` to work just like `copy` when `dest` is a folder.
win_copy
win_template
win_updates
=> Use FQCN for action plugin modules and align copy behaviour

plugins/modules/win_dsc.ps1, plugins/modules/win_dsc.py, tests/integration/targets/win_dsc/tasks/tests.yml
The `Invoke-DscResource` creates a CimSession in the background but there is no way to configure the port or protocol to use so it will only work when a HTTP WSMan listener is active on the port configured by `Get-Item -LiteralPath WSMan:\localhost\Client\DefaultPorts\HTTP`.
Instead of giving a cryptic error from the cmdlet this PR will give users a better message. It also adds this requirement to the docs for the module.
Fixes https://github.com/ansible-collections/ansible.windows/issues/32
win_dsc
=> win_dsc: better error when WSMan not available

plugins/modules/setup.ps1
The changes in https://github.com/ansible/ansible/pull/56279 fixed the stray period at the end of a host when not joined to a domain but it is returning the domain name and not the actual primary DNS suffix of the host.
This PR keeps that original logic but changes the source of the FQDN dns part back to the original IPGlobalProperties method.
setup
=> Use original logic for FQDN hostname builder

plugins/modules/win_service.ps1, plugins/modules/win_service.py, plugins/modules/win_service_info.ps1, tests/integration/targets/win_service/tasks/tests.yml, tests/integration/targets/win_service_info/defaults/main.yml
This is a refactor of the `win_service` module that adds the following
* Uses the `Ansible.Basic.AnsibleModule` wrapper
* Support for specifying virtual accounts and managed service accounts on the `username` option
* Separate `password` from `username`, they are no longer required to be set together so each can be updated individually
* Added `diff` output to better see what has changed
* Tidied up implementation to use the new SCManager C# util which opens up further configuration options like failure handling, service sid info, and lots of other config options
* This also removes the 3 different ways we set things currently into the 1 unified interface that calls the Win32 APIs directly.
This PR also tweaks `win_service_info` in the following ways
* Supports `name` referencing a …
=> Refactor win_service to use newer Ansible.Basic util

plugins/modules/win_service.ps1, plugins/modules/win_service.py, tests/integration/targets/win_service/tasks/error_control.yml, tests/integration/targets/win_service/tasks/failure_actions.yml, tests/integration/targets/win_service/tasks/load_order_group.yml, tests/integration/targets/win_service/tasks/main.yml, tests/integration/targets/win_service/tasks/pre_shutdown_timeout_ms.yml, tests/integration/targets/win_service/tasks/required_privileges.yml, tests/integration/targets/win_service/tasks/service_type.yml, tests/integration/targets/win_service/tasks/sid_info.yml, tests/integration/targets/win_service/tasks/tests.yml, tests/integration/targets/win_service_info/tasks/main.yml
Now that the module has been refactored with https://github.com/ansible-collections/ansible.windows/pull/34 we can start adding more features into it. This PR adds the following options to win_service
* error_control
* failure_actions
* failure_actions_on_non_crash_failure
* failure_command
* failure_reboot_msg
* failure_reset_period_sec
* load_order_group
* pre_shutdown_timeout_ms
* required_privileges
* service_type
* sid_info
With this change the only things missing from the win_service module are:
* Triggers
* This is quite complex and potentially warrants being in its own module
* Security Descriptors
* I'm hoping to create a generic framework for `win_<resource>_sd` modules that this will fall under
* Preferred nodes
* Only valid for NUMA enabled hosts, cannot really test in CI
* …
=> win_service: feature bonanza

plugins/filter/quote.py, tests/unit/plugins/filter/test_quote.py
When escaping quotes for a PowerShell argument we need to double up on more than just `'`. We also need to escape `'`, `’`, `‘`, `‚`, and `‛` by just repeating the char. Also fixes a bug when trying to escape `"` in a cmd argument where the escaped value need to be `\^"` and not just `^"`.
Fixes https://github.com/ansible-collections/ansible.windows/issues/45
quote
=> Fix up ps quoting escape rules

plugins/doc_fragments/web_request.py, plugins/module_utils/WebRequest.psm1, plugins/modules/win_get_url.ps1, plugins/modules/win_get_url.py, plugins/modules/win_package.ps1, plugins/modules/win_package.py, plugins/modules/win_uri.ps1, plugins/modules/win_uri.py, tests/integration/targets/module_utils_WebRequest/aliases, tests/integration/targets/module_utils_WebRequest/library/web_request_test.ps1, tests/integration/targets/module_utils_WebRequest/meta/main.yml, tests/integration/targets/module_utils_WebRequest/tasks/main.yml
Creates a copy of `Ansible.ModuleUtils.WebRequest` in the collection and migrates the 3 modules that use it to this copy. This starts the slow migration of module utils from ansible.windows into this collection.
Requires https://github.com/ansible/ansible/pull/69719 to be merged before this can work.
win_get_url
win_package
win_uri
=> Added WebRequest util modelled after the Ansible WebRequest util

plugins/modules/win_domain.ps1, plugins/modules/win_domain_controller.ps1
A mismatch in the required features between win_domain and win_domain_controller will lead to unnecessary reboots/feature installations when both modules are used (which is the typical case). The comments show win_domain incorrectly assumed that AD-Domain-Services includes RSAT-AD-Tools and RSAT-AD-AdminCenter (not the case, at least for Win 2019). Now both will check for the same necessary features in a domain controller.
win_domain and win_domain_controller
=> win_domain and win_domain_controller necessary features

plugins/modules/setup.ps1, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt
We run PSScriptAnalyzer at 1.18.0 in the default test container and it was only recently that PSSA added support for suppressing custom rules in the code. For now we just need to continue ignoring it globally for the file until we update the PSSA version used.
sanity
=> Fix up invalid sanity check not supported by our PSSA version

changelogs/fragments/win_domain_computer.yml, changelogs/fragments/win_regedit-basic-dep.yml, meta/runtime.yml, plugins/modules/setup.ps1, plugins/modules/win_domain_controller.ps1, plugins/modules/win_domain_controller.py, plugins/modules/win_regedit.ps1, plugins/modules/win_regedit.py, tests/integration/targets/win_regedit/tasks/tests.yml
After migrating the code from ansible/ansible to the collection we need to change any Ansible version deprecations to date deprecations. To easily support this the module should also be using the Ansible.Basic wrapper. Also adds the `runtime.yml` that specifies the versions of Ansible the collection supports.
win_domain_controller
win_regedit
Have manually test `win_domain_controller` outside of CI with the following Vagrantfile and playbook
```ruby
Vagrant.configure("2") do |config|
config.vm.define "dc01" do |dc|
dc.vm.box = "jborean93/WindowsServer2019"
dc.vm.network :private_network, ip: "192.168.56.40"
dc.vm.hostname = "dc01"
dc.vm.provider :libvirt do |lv|
lv.cpus = 4
lv.memory = 8192
end
end
config.vm.define "dc02" do |cd|
cd.vm.box = …
```
=> Migrate version deprecations to dates, added runtime

changelogs/fragments/66-win_dsc-load-assemblies.yml, plugins/modules/win_dsc.ps1, tests/integration/targets/win_dsc/files/xTestClassDsc/1.0.0/xTestClassDsc.psd1, tests/integration/targets/win_dsc/files/xTestClassDsc/1.0.0/xTestClassDsc.psm1, tests/integration/targets/win_dsc/tasks/main.yml, tests/integration/targets/win_dsc/tasks/tests.yml
Make sure we always load the module so it loads its required assemblies before importing the DSC resource.
Fixes https://github.com/ansible-collections/ansible.windows/issues/66
win_dsc
=> win_dsc - load module first for their defined assemblies

plugins/modules/win_command.py, plugins/modules/win_copy.py, plugins/modules/win_file.py, plugins/modules/win_find.py, plugins/modules/win_get_url.py, plugins/modules/win_group.py, plugins/modules/win_ping.py, plugins/modules/win_reboot.py, plugins/modules/win_service.py, plugins/modules/win_shell.py, plugins/modules/win_stat.py, plugins/modules/win_tempfile.py, plugins/modules/win_template.py, plugins/modules/win_updates.py, plugins/modules/win_uri.py, plugins/modules/win_user.py, plugins/modules/win_wait_for.py
Any references to builtin modules should contain the `ansible.builtin` prefix.
https://github.com/ansible-collections/overview/issues/45#issuecomment-648405709
many
=> Fix up builtin module references

changelogs/fragments/win_user-refactor.yml, plugins/modules/win_user.ps1, plugins/modules/win_user.py, tests/integration/targets/win_user/files/lockout_user.ps1, tests/integration/targets/win_user/tasks/tests.yml
A refactor of the win_user module that adds the following features
* Adds check mode support
* Adds diff mode support
* Uses `Ansible.Basic.AnsibleModule`
* Adds the `home_directory` option
* Adds the `login_script` option
* Adds the `profile` option
It also makes a change to how the imdepotency checks work for `fullname` and `description`. Because the checks were case insensitive now they are case sensitive. While this is a breaking change in behaviour I believe the new behaviour is correct and wouldn't break existing playbooks.
I still need to expand the integration tests to cover the new options and things like the check mode behaviour.
Fixes https://github.com/ansible-collections/ansible.windows/issues/24
win_user
=> win_user refactor

changelogs/fragments/win_copy-single-fix.yml, plugins/action/win_copy.py, tests/integration/targets/win_copy/tasks/tests.yml
When copying a folder from the Ansible controller to the remote host and only a single file needs to be copied across, the plugin will fail with:
```
The full traceback is:Traceback (most recent call last):
File "/home/jborean/dev/ansible/lib/ansible/executor/task_executor.py", line 159, in run
res = self._execute()
File "/home/jborean/dev/ansible/lib/ansible/executor/task_executor.py", line 574, in _execute
result = self._handler.run(task_vars=variables)
File "/home/jborean/dev/ansible_collections/ansible/windows/plugins/action/win_copy.py", line 503, in run
result.update(self._copy_single_file(file_src, dest, original_basename, file_dest,
UnboundLocalError: local variable 'original_basename' referenced before assignment
fatal: [2019]: FAILED! => 
msg: Unexpected failure during module …
```
=> win_copy - fix copying single file in a dir copy

changelogs/fragments/113-win_environment-multi-var.yaml, plugins/modules/win_environment.ps1, plugins/modules/win_environment.py, tests/integration/targets/win_environment/defaults/main.yml, tests/integration/targets/win_environment/tasks/cleanup.yml, tests/integration/targets/win_environment/tasks/main.yml
- Adds dict option `variables` so you can set multiple key/value pairs without looping over the module
- Previous `name` and `value` options still work
- Added tests for the new option
- Added a new return value for seeing the changes on all vars affected
- Existing return values still work correctly on single vars
win_environment
Usage:
```yaml
- win_environment:
state: present
level: machine
variables:
VAR_ONE: value 1
COOL_VAR_NAME: uncool value tho
VAULT_ADDR: https://127.0.0.1
```
Internals:
- A function handles the setting and before/after/changed status of individual env vars
- Single name/value option set is implemented the same as passing in a single key/value dict to `variables` internally, which keeps testing relatively simple
- Fully backward compatible
=> win_environment - add a dictionary option to set multiple values at once

plugins/module_utils/Process.cs, plugins/module_utils/Process.psm1, plugins/modules/win_package.ps1, plugins/modules/win_package.py, tests/integration/targets/module_utils_Process/aliases, tests/integration/targets/module_utils_Process/library/process_cs_tests.ps1, tests/integration/targets/module_utils_Process/library/process_pwsh_tests.ps1, tests/integration/targets/module_utils_Process/meta/main.yml, tests/integration/targets/module_utils_Process/tasks/main.yml, tests/integration/targets/setup_win_printargv/files/PrintArgv.cs, tests/integration/targets/setup_win_printargv/tasks/main.yml, tests/integration/targets/win_command/tasks/main.yml
Adds a slightly modified version of `Ansible.Process` and `Ansible.ModuleUtils.CommandUtil` to the collection. This util should be the one used for any new work going forward as it can include new features without waiting on ansible-base to be updated.
Adds the option `wait_for_children` to `win_package` that can be used to make sure any child processes spawned by the installer are finished before `win_package` returns. This is an opt-in behaviour as it could cause hangs in existing installers if they spawn any child processes that never exit.
Fixes https://github.com/ansible-collections/ansible.windows/issues/116
Need to add some tests for the new module_utils.
win_package
=> Added Process util and add option to wait for child processes to be done for win_package

plugins/modules/win_certificate_store.py
Specify `become_user: SYSTEM` when importing certificates to be used with IIS.
Failure to do this may result in ⬇️ when trying to use this certificate in an IIS binding.
```
A specified logon session does not exist. It may already have been terminated.
```
`ansible.windows.win_certificate_store`
When running this snippet (which uses ` ansible.windows.win_dsc` example [`Create IIS Website`](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_dsc_module.html#examples)):
```
- name: Import certificate
ansible.windows.win_certificate_store:
path: 'C:\{{ certname }}.pfx'
key_exportable: false
file_type: pkcs12
state: present
store_location: LocalMachine
register: certificate
- name: Create IIS Website
ansible.windows.win_dsc:
resource_name: xWebsite …
```
=> become_user SYSTEM when importing certificate for IIS 

tests/integration/targets/module_utils_Process/library/process_pwsh_tests.ps1
The nightly CI run was failing on this test and this PR fixes that problem.
The reason why the CI run failed but the tests ran perfectly fine through a normal PR is because the nightly run enables coverage. When coverage is enabled Ansible will create a file for the module to run and invoke it like `C:\path\to\module.ps1`. The fix for this is to not create it with a new closure, there's no reason why that was needed here so removing simplifies everything.
The reason why `GetNewClosure()` causes a failure here is because it only copies modules and not functions in the current scope. When run it only has access to those vars in that scope at the time and whatever is set globally. In this case the function `Assert-Equals` was not defined globally and is only available in the local scope that …
=> Fix broken tests when run with coverage

tests/integration/targets/win_command/tasks/main.yml, tests/integration/targets/win_get_url/tasks/main.yml, tests/integration/targets/win_get_url/tasks/tests_url.yml, tests/integration/targets/win_package/tasks/main.yml, tests/integration/targets/win_package/tasks/msix_tests.yml, tests/integration/targets/win_service/tasks/main.yml, tests/integration/targets/win_service_info/tasks/main.yml
Sometimes CI can fail to download files from an external source which fails the whole thing. This adds a retry to these tasks to hopefully reduce the number of unstable test results we get from these issues.
tests
=> Stabilise CI

changelogs/fragments/win_find-hidden.yml, plugins/modules/win_find.ps1, tests/integration/targets/win_find/tasks/tests.yml
The `find` module returns both hidden and normal files when `hidden: yes`, this PR changes `win_find` to match that behaviour.
Fixes https://github.com/ansible-collections/ansible.windows/issues/130.
win_find
=> win_find - return normal files with hidden: yes

changelogs/fragments/win_service-pwsh5.0.yaml, plugins/modules/win_service.ps1, plugins/modules/win_service_info.ps1
I could only ever replicate this issue on PowerShell 5.0 (not 5.1) which has been yanked from existence by Microsoft and really only available on older Windows 10 builds. There's some engine error when you try to cast to an enum inside a group then call `ToString()` on it. A quick reproducer that will fail on WMF 5.0 is
```powershell
[IO.FileAttributes]$a = 'Archive'
([IO.FileAttributes]$a).ToString()
```
There was an alternative solution proposed but this keeps the code somewhat tidier.
Fixes https://github.com/ansible-collections/ansible.windows/issues/125
win_service
win_service_info
=> win_serivce - fix pwsh 5.0 bug

changelogs/fragments/win_package-readonly.yaml, plugins/modules/win_package.ps1, tests/integration/targets/win_package/tasks/msi_tests.yml, tests/integration/targets/win_package/templates/mount.txt.j2, tests/integration/targets/win_package/templates/mount_readonly.txt.j2, tests/integration/targets/win_package/templates/umount.txt.j2
When installing from a readonly location the `win_package` module fails as it cannot add the ACE for the `SYSTEM` account to the path. This may not be necessary so we can just ignore a failure and wait until it either succeeds or fails later on.
Fixes https://github.com/ansible-collections/ansible.windows/issues/142
win_package
=> win_package - fix installs from readonly location

changelogs/fragments/win_service.yaml, plugins/modules/win_service.ps1, plugins/modules/win_service.py, plugins/modules/win_service_info.ps1, tests/integration/targets/win_service/tasks/driver.yml, tests/integration/targets/win_service/tasks/main.yml, tests/integration/targets/win_service/tasks/tests.yml
Specify explicit permissions when opening the service as we do not require all access. Also allow opening driver services which were being excluded by `Get-Service` due to how it was being called.
Fixes https://github.com/ansible-collections/ansible.windows/issues/115
Fixes https://github.com/ansible-collections/ansible.windows/issues/118
win_service
win_service_info
=> win_service - Open drivers and relax required perms

.azure-pipelines/azure-pipelines.yml, tests/utils/shippable/shippable.sh
Removes the need for the PATH hack in the testing container
=> Update AZP test container for PATH fixes

changelogs/fragments/win_service-sid.yml, plugins/modules/win_service.ps1
Fix the code that splits netlogon account names to split by `\` and not `\.`.
Fixes https://github.com/ansible-collections/ansible.windows/issues/156
win_service
=> win_serivce - Fix up username split code

changelogs/fragments/setup_empty_path.yml, plugins/modules/setup.ps1, tests/integration/targets/win_setup/tasks/main.yml
When scaning the `PATH` env var we need to skip blank entries as it causes a binding issue when joining to `Join-Path -Path`.
Fixes https://github.com/ansible-collections/ansible.windows/pull/78#issuecomment-745229594
setup
=> setup - handle PATHs with blank entry

docs/ansible.windows.win_shell_module.rst
Type within Examples: 'comand' to 'command'
win_shell
```paste below
```
=> win_shell_module: fixed the typo 'comand' in examples

plugins/modules/win_updates.py
Added "Upgrades" to the category name
win_updates
During the Windows 10 update, I noticed that some patches could not be applied.
The following 12 categories are picked up as the main categories in the document.
(Application, Connectors, Critical Updates, Definition Updates, Developer Kits, Feature Packs, Guidance, Security Updates, Service Packs, Tools, Update Rollups and Updates.)
However, the following patches only exist in the "Upgrades" category.
```json
"fbcf5b50-4e5f-4be7-9c72-e9d505860d10": {
"categories": [
"Upgrades"
],
"filtered_reason": "category_names",
"id": "fbcf5b50-4e5f-4be7-9c72-e9d505860d10",
"installed": false,
"kb": [
"4592449"
]
```
I suggest that anyone who browses the documentation can apply all patches.
=> update documment for category_names

changelogs/fragments/setup-virtual.yml, plugins/modules/setup.ps1
While not as complex as `module_utils/facts/virtual/linux.py` used by the Python setup module this PR adds a few more virtualization types based on the code there.
Fixes https://github.com/ansible-collections/ansible.windows/issues/171
setup
=> setup - added more virtualization types

changelogs/fragments/win_package-creates-version.yml, plugins/modules/win_package.ps1, tests/integration/targets/win_package/tasks/registry_tests.yml
If `creates_version` was set then the code was set to fail when `creates_path` was non-existent. Instead we should only be failing if `creates_path` is the path to a directory, if it doesn't exist then we consider the package to not be installed.
Fixes https://github.com/ansible-collections/ansible.windows/issues/169
win_package
=> win_package - fix failure on creates_version

changelogs/fragments/win_package-msi-code.yml, plugins/modules/win_package.ps1
Make sure we ignore the machine state when trying to open an msi. This allows us to get the product code even if it's already been installed under a different package.
Fixes https://github.com/ansible-collections/ansible.windows/issues/166
win_package
=> win_package - fix msi product code check

plugins/modules/win_updates.py
I get it that the win_updates module doesn't support SCCM.  
So this PR will remove SCCM from the documentation block, and add about SCCM doesn't support to notes.
see: https://github.com/ansible-collections/ansible.windows/issues/194
win_updates
```
```
=> win_updates - Update the documentation block

changelogs/fragments/setup-epoch.yml, plugins/modules/setup.ps1
While a PR set `epoch_int` to the value of `$epoch` we never actually defined `$epoch`. This PR fixes that problem.
Fixes https://github.com/ansible-collections/ansible.windows/issues/183
setup
=> setup - correct epoch_int calculation

changelogs/fragments/win_user-groups.yml, plugins/modules/win_user.ps1, plugins/modules/win_user.py, tests/integration/targets/win_user/tasks/tests.yml
Changes the internal group comparison logic to work with SIDs rather than the human name. Also exposes the ability to specify a group using it's SID which helps for localisation issues and the user wants to be more explicit.
Fixes https://github.com/ansible-collections/ansible.windows/issues/153
Fixes https://github.com/ansible-collections/ansible.windows/issues/168
Supersedes https://github.com/ansible-collections/ansible.windows/pull/154
win_user
=> win_user - use SIDs for group comparison

changelogs/fragments/win_certificate_store_service.yml, plugins/modules/win_certificate_store.ps1, plugins/modules/win_certificate_store.py, tests/integration/targets/win_certificate_store/tasks/test.yml
Added the ability to manage the certificate store for a Windows service. Also made the `store_name` a free form field so it can manage 3rd party stores that are present.
I initially tried to allow creating and removing of custom stores in this module but the lack of documentation around moving a certificate store stopped me. I could remove the store once but it was never removed completely due to it being duplicated in various locations. This functionality will require more investigation before it can be implemented.
win_certificate_store
=> win_certificate_store - added ability to manage a service store

changelogs/fragments/win_template-dest_path.yml, plugins/action/win_template.py
The change in Ansible https://github.com/ansible/ansible/pull/73924 added a positional argument in between source and dest_path meaning the call in `win_template` was treating `dest` another another `source` option. Instead we use the kwarg to ensure any future additions won't affect the code here anymore. I checked both stable-2.10 and stable-2.9 to make sure `generate_ansible_template_vars` had the kwarg `dest_path` so this change will still work on those versions.
win_template
=> win_template - Fix ansible internal call that changed slightly in devel

plugins/module_utils/Process.cs, plugins/module_utils/Process.psm1, plugins/modules/win_powershell.ps1, plugins/modules/win_powershell.py, plugins/modules/win_shell.py, tests/integration/targets/module_utils_Process/library/process_cs_tests.ps1, tests/integration/targets/win_powershell/aliases, tests/integration/targets/win_powershell/meta/main.yml, tests/integration/targets/win_powershell/tasks/main.yml, tests/integration/targets/win_powershell/tasks/tests.yml, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt
Add a module that can be used to execute PowerShell script like `win_shell`. Where this differs with `win_shell` is it adds the outputted objects from the powershell script as a structured return value like:
```powershell
- ansible.windows.win_powershell:
script: |
Get-Service | Select Name, @{N='Status'; E={ $_.Status.ToString() }}
register: service_info
- ansible.windows.win_service:
name: '{{ item.Name }}'
state: started
with_items: '{{ service_info.output }}'
when: '{{ item.Status != "Running" }}'
```
It also adds a few more benefits like
* Each individual stream record in the registered output
* Error records can be parsed as a structured object
* Warning/Verbose/Debug records are a list of string
* Information records are also a structured object
* Can easily pass in objects as …
=> win_powershell - Added module for executing powershell scripts

changelogs/fragments/win_reboot-dep.yml, changelogs/fragments/win_reboot-refactor.yml, plugins/action/win_reboot.py, plugins/filter/quote.py, plugins/modules/win_reboot.py, plugins/plugin_utils/_quote.py, plugins/plugin_utils/_reboot.py, tests/integration/targets/win_reboot/tasks/main.yml
A refactor of the win_reboot plugin. It changes the following
* Stops relying on `reboot` that is in ansible-base in case that makes an incompatible change
* Move the reboot specific components to an internal plugin util to make it easy for other action plugins to call
* Ensure the correct and documented return values are returned on a failure
* Return stdout/stderr/rc from get last boot time failures as separate keys for easier parsing
* Try to handle connection failures with requests based connections (winrm/psrp) where they don't catch those exceptions properly
Fixes https://github.com/ansible-collections/ansible.windows/issues/27
Fixes https://github.com/ansible-collections/ansible.windows/issues/36
Fixes https://github.com/ansible-collections/ansible.windows/issues/62
- Bugfix Pull …
=> win_reboot - refactor and stabilise

changelogs/fragments/win_certificate_store-ca.yml, plugins/modules/win_certificate_store.ps1, tests/integration/targets/win_certificate_store/tasks/test.yml
In the past we used a .NET method that translated `[Security.Cryptography.X509Certificates.StoreName]::CertificateAuthority` to the `CA` store. Now that we open the handle manually and we just pass the string in directly we still need to ensure that `store_name: CertificateAuthority` refers to the `CA` store just like it did before.
Fixes https://github.com/ansible-collections/ansible.windows/pull/216
win_certificate_store
=> win_certificate_store - fix CertificateAuthority -> CA

docs/ansible.windows.win_package_module.rst, plugins/modules/win_package.py
Including guidance from https://github.com/ansible/ansible/issues/50221#issuecomment-449199876 regarding the handling of list arguments. 
I've spent quite a lot of time trying to figure out an issue regarding the use of list arguments with win_package. This [issue](https://github.com/ansible/ansible/issues/50221#issuecomment-449199876) had some really good advice from @jborean93 on how to properly use list arguments and I thought this would be a useful addition to the documentation just in case anyone else runs into something similar.
ansible.windows.win_package
The following task will fail with a return code of 87.
```- name: Install MSBuild Tools
win_package:
path: "https://download.visualstudio.microsoft.com/download/pr/9665567e-f580-4acd-85f2-bc94a1db745f/3580c7d8c4 …
```
=> Add more detail about list arguments

plugins/modules/win_service.py
Tweaks the wording for the `win_service` docs.
Supersedes https://github.com/ansible-collections/ansible.windows/pull/224
win_service
=> win_service - fix up typo for docs

plugins/plugin_utils/_reboot.py
This particular msg is displayed in a potentially long running and frequent loop. To avoid spamming the output with too many messages this is changed to only show with `-vvv`.
win_reboot
=> Change the verbosity level of this reboot msg

changelogs/fragments/win_reboot-flaky-connection.yml, plugins/plugin_utils/_reboot.py
A few tasks that require a reboot may leave the connection in a bad state. We try at least 3 times to run the first command when getting the boot timeout to help alleviate this issue. It's not a guaranteed fix as the connection error may happen in the previous task but that requires some more substantial work to implement properly.
Also broadens the scope of request errors that are considered a connection issue after more use in the real world.
win_reboot
=> win_reboot - handle flaky connection at the start

changelogs/fragments/win_state-datetime.yml, plugins/modules/win_stat.ps1
Epoch timestamps should be based on UTC and not the local timezone. While this change is technically a breaking change the format of the value doesn't change so it will still be parsed in the same way. It also aligns the module with the behaviour of `stat` and what most people would expect from a epoch based timestamp. Due to these reasons it's being made as a bugfix.
Fixes https://github.com/ansible-collections/ansible.windows/issues/240
win_stat
=> win_stat - return time offets from UTC

plugins/modules/win_dsc.py
The Local Configuration Manager should be disabled on Windows hosts when using the `win_dsc` module. This PR adds this note as well as a link to e Microsoft article on how to disable LCM using PowerShell.
Fixes https://github.com/ansible-collections/ansible.windows/issues/128
Fixes https://github.com/ansible-collections/ansible.windows/issues/233
win_dsc
=> win_dsc - Add docs for win_dsc and LCM configuration

changelogs/fragments/win_dsc-locale.yml, plugins/modules/win_dsc.ps1
The `PSDesiredStateConfiguration` fails to import when the UI culture doesn't match the installed UI culture. This works around this issue as best as possible by temporarily changing the current UI back and also not treat ever error as fatal.
Even if `$ErrorActionPreference = 'Continue'` masks a real fatal error (it shouldn't), the subsequent call to `Get-DscResource` will attempt to re-import it under the existing strict preference causing the same failure as today.
Fixes https://github.com/ansible-collections/ansible.windows/issues/83
win_dsc
=> win_dsc - fix locale problems

plugins/modules/win_regedit.py
`str` should be `string`, otherwise this error will occur:
`value of type must be one of: none, binary, dword, expandstring, multistring, string, qword. Got no match for: str`
win_regedit
=> Fix typo in the example of windows.win_regedit

changelogs/fragments/260-description-checkmode.yml, plugins/modules/win_group.ps1, tests/integration/targets/win_group/tasks/main.yml
When a group does not exist yet, trying to set the description in check_mode fails because the object does not exist yet.
This change moves the description setting out of check_mode.
Fixes #258 
Includes tests for this issue
win_group.ps1
```paste below
```
=> win_group - fixed setting of group description in check_mode runs

changelogs/fragments/win_user-domain.yml, plugins/modules/win_user.ps1
I get an error in the win_user module when creating a local user on servers in AD: "Failed to validate the user's credentials: Failed to logon username (Incorrect function, Win32ErrorCode 1 - 0x00000001)". This commit fixes this problem.
I am getting an error in the win_user module when creating a local user on servers in AD: "Failed to validate user credentials: Could not login with username (invalid function, Win32ErrorCode 1 - 0x00000001)"
This error is sent by the [Ansible.AccessToken.TokenUtil] :: LogonUser function. This function calls LogonUserW from the Windows API. Description of this function is here https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-logonuserw
And in this description for the lpszDomain parameter it says:
lpszDomain
A pointer to a …
=> Fix for "Failed to validate the user's credentials"

changelogs/fragments/win_updates-executionpolicy.yml, plugins/action/win_updates.py
The module invokes the PowerShell script inline but if the system execution policy settings are too restricted. To do this it reads the specified script as a string and executes that as a scriptblock.
Fixes https://github.com/ansible-collections/ansible.windows/issues/272
win_updates
=> win_updates - bypass execution policy checks

changelogs/fragments/reboot_error_outside_block.yml, plugins/plugin_utils/_reboot.py
Small fix for last_error raising in reboot util (python 3 compatibility)
_reboot.py
Original variable `e` is deleted outside the except block
https://stackoverflow.com/questions/24271752/except-clause-deletes-local-variable
Here's a simple example that reproduces the problem:
```python
def main():
try:
raise Exception("msg")
except Exception as e:
print(e)
raise e
main()
```
=> win_reboot - fix last_error raising

changelogs/fragments/283-win_dns_client_IPv6_DNS.yml, plugins/modules/win_dns_client.ps1
Fixes #283 
Using win_dns_client failed when an IPv6 interface dns server was configured.
Bugfix Pull Request
win_dns_client.ps1 module used by win_dns_client.
=> Fix error when using win_dns_client with an IPv6 dns server

changelogs/fragments/add-type-env.yml, plugins/modules/win_file.ps1, plugins/modules/win_find.ps1, plugins/modules/win_stat.ps1, plugins/modules/win_updates.ps1, plugins/modules/win_whoami.ps1, tests/integration/targets/win_file/tasks/main.yml, tests/integration/targets/win_stat/defaults/main.yml, tests/integration/targets/win_stat/meta/main.yml, tests/integration/targets/win_stat/tasks/main.yml, tests/integration/targets/win_stat/tasks/tests.yml
Calling `Add-Type` with the env var `LIB` set to an invalid PATH breaks the compilation and thus fails the module. This PR changes modules to use `Add-CSharpType` which fixed this problem https://github.com/ansible/ansible/pull/75698. The `win_find` and `win_stat` modules are a bit special because they still call a builtin module_util so they manually unset the env var until the code in Ansible itself has been fixed.
Fixes https://github.com/ansible-collections/ansible.windows/issues/297
win_file
win_find
win_stat
win_updates
win_whoami
=> Fix LIB env var conflicts

plugins/modules/win_copy.ps1
In case of remote_dest, handle variables for folder copy the same way as file copy, so that Get-FileSize is executed at the proper level.
win_copy
Set up a playbook that will copy a folder into C:\ with remote_src enabled
```yaml
- name: Copy Tools Folder
win_copy: 
src: \\fileserver\sharedfolder\Tools
dest: C:\
remote_src: yes
```
The error looks as below. It tries to go into some symbolic links under `C:\Document and Settings\<some user>\AppData\Local`: `ApplicationData` links back into `AppData\Local` and leads into an infinite loop.
The issue is that the name of the folder that is being copied is not appended in $remote_dest so `Get-FileSize` is run on `C:\` instead of `C:\subfolder`.
We could confirm that this bug is absent when running a version of …
=> Fix issues when copying folder with remote_dest

changelogs/fragments/win_copy-dest-calc-fix.yml, plugins/modules/win_copy.ps1, tests/integration/targets/win_copy/tasks/remote_tests.yml
Improve the error handling of the dest size check after copying a file remotely.
Fixes https://github.com/ansible-collections/ansible.windows/issues/298
win_copy
=> win_copy - improve dest size check for weird edge cases

changelogs/fragments/win_command-shell-time.yml, plugins/modules/win_command.ps1, plugins/modules/win_shell.ps1
Fix of issue https://github.com/ansible-collections/ansible.windows/issues/303
Changed output time format in modules win_command and win_shell from 12H to 24H
Fixes #303
win_command
win_shell
```paste below
```
=> Change output time format from 12H to 24H.

.gitignore, .vscode/.env, .vscode/extensions.json, .vscode/settings.json, tests/unit/conftest.py
Now that Ansible from a source checkout can be installed with `pip install -e .` we can simplify the logic in the collection loader plugin used in vscode.
Also adds PowerShell auto formatting to help make it easier to fix sanity problems.
ansible-test unit
=> Simplify unit test runner

changelogs/fragments/win_updates-return.yml, plugins/action/win_updates.py, plugins/modules/win_updates.ps1, plugins/modules/win_updates.py, tests/integration/targets/win_updates/tasks/main.yml, tests/unit/plugins/action/test_win_updates.py
The `win_updates` refactor in `1.7.0` changed the return value of `updates` and `filtered_updates` from a dict to a list. To ease the transition to the collection from users of Ansible 2.9 or ealier this update reverts the changing of these values back to what it was before.
This is technically a breaking change but it's to rectify something that shouldn't have changed in the first place.
Fixes https://github.com/ansible-collections/ansible.windows/issues/307
win_updates
=> win_updates - fix incorrect return value

changelogs/fragments/win_updates-sleep.yml, plugins/modules/win_updates.ps1
The module will not tell the host every minute not to go to sleep when running the long async tasks for Windows Updates.
Fixes https://github.com/ansible-collections/ansible.windows/issues/310
win_updates
=> win_updates - prevent host from sleeping

.github/workflows/stale.yml
Adds a github workflow to mark stale PRs after 4 weeks and close them 2 weeks after that.
=> Add stale PR handler

changelogs/fragments/win_powershell.yml, plugins/modules/win_powershell.ps1, plugins/modules/win_powershell.py
Add $module.Verbosity to 'Ansible' object.
ansible.windows.win_powershell
Since $module is not exposed to the script, the script cannot know Ansible's running verbosity. This pull adds the Verbosity from $module to $Ansible and allows a script author to modify their VerbosePreference and/or DebugPreference based on the $Ansible.Verbosity value. This should prove useful to when we need to troubleshoot problems with scripts instead of just win_powershell itself.
``` yaml
---
- name: Define when to enable Verbose/Debug output
ansible.windows.win_powershell:
script: |
if ($Ansible.Verbosity -ge 3) {
$VerbosePreference = "Continue"
}
if ($Ansible.Verbosity -eq 5) {
$DebugPreference = "Continue"
}
Write-Output "Hello World!"
Write-Verbose "Hello …
```
=> Add Verbosity to 'Ansible' object.

changelogs/fragments/win_updates-execution-policy.yml, plugins/modules/win_updates.ps1
If a host has a restrictive execution policy set through GPO then the `win_updates` module will fail to start `task.ps1` which is run through the task scheduler. By having the new process read the file manually and invoke it using a scriptblock it can avoid this restriction and run like normal.
win_updates
=> win_updates - fix execution policy restrictions

plugins/modules/win_user_right.py
Further clarifies the recommendation to use the `.\account` or `SERVERNAME\account` format when dealing with local users and groups.
Fixes https://github.com/ansible-collections/ansible.windows/issues/316
win_user_right
=> win_user_right - update docs on user domain prefix

changelogs/fragments/win_reboot-pre-delay.yml, plugins/action/win_reboot.py, plugins/modules/win_reboot.py
CI is sometimes seeing a problem with the RPC server not being online when attempting a reboot. This adds a simple retry option in the reboot command if this comes up again.
win_reboot
=> win_reboot - enforce minimum pre reboot time to 2 seconds

plugins/modules/win_dns_client.py, plugins/modules/win_feature.py, plugins/modules/win_group_membership.py, plugins/modules/win_path.py, plugins/modules/win_wait_for.py
Devel introduced a new santiy check to ensure any doc members with `type: list` must also have a `elements: ...` entry to denote the type of each list element.
=> Fix sanity issues

changelogs/fragments/setup_more_interface_data.yml, plugins/modules/setup.ps1
setup - Added ipv4, ipv6, mtu and speed data to ansible_interfaces
setup
This add some more useful data to ansible_interfaces.
=> setup - Added ipv4, ipv6, mtu and speed data to ansible_interfaces

.azure-pipelines/azure-pipelines.yml, tests/sanity/ignore-2.14.txt
Ansible has just bumped versions in the devel branch to 2.14 which requires a new sanity ignore file. This adds that file and ensures we still test with the newly created stable-2.13.
=> add new stable branch and fix up 2.14 santiy ignores

changelogs/fragments/environment_notify.yml, plugins/modules/win_environment.ps1, plugins/modules/win_path.ps1, plugins/modules/win_path.py
Broadcast the `WM_SETTINGCHANGE`message to top level windows when an environment variable has changed. This replicates what Windows does when changing the environment variables through the GUI. While technically a change in behaviour I cannot imagine why this shouldn't be automatically done so I didn't add a new option to toggle this behaviour.
This also updates `win_path` to use the newer module style.
Fixes https://github.com/ansible-collections/ansible.windows/issues/348
win_environment
win_path
=> win_environment path - Notify on environment change

docs/ansible.windows.win_find_module.rst, plugins/modules/win_find.py
Corrects an error in the documentation for win_find_module where the returned value has an incorrect sample.
Current sample shows what would be the owner of the file, but should show a path to the found file.
win_find_module
=> docs win_find_module correct sample for value path

changelogs/fragments/win_stat-share-slash.yml, plugins/modules/win_find.ps1, plugins/modules/win_stat.ps1
The proposed change addresses a consistent, reproducible error with the win_stat module.
Without this change, it is impossible to have the module work in situations where the path contains single quotes: `'`
This PR simply enforces the recommended syntax for the Get-CimInstance command, as per the documentation:
```
If the value specified contains double quotes (“), single quotes (‘), or a backslash (\), you must escape 
those characters by prefixing them with the backslash (\) character.
```
win_stat
Result before the change:
```
The full traceback is:
Invalid query 
At line:127 char:23
+ ... hare_info = Get-CimInstance -ClassName Win32_Share -Filter "Path='$($ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : …
```
=> Make sure to escape single quotes in win_stat path

.azure-pipelines/azure-pipelines.yml, README.md, changelogs/fragments/ansible-version-bump.yml, galaxy.yml, meta/runtime.yml
Raises the minimum ansible version to 2.11 now that 2.10 is end of life
=> Raise minimum Ansible version to 2.11

changelogs/fragments/win_package-msix-legacy.yml, plugins/modules/win_package.ps1
The msix provider only works on Server 2012 or newer. The installed check will only check with the `msix` provider in `auto` if the required cmdlets are present.
Fixes https://github.com/ansible-collections/ansible.windows/issues/362
=> win_package - skip msix on older hosts

changelogs/fragments/setup-invalid-PATH.yml, plugins/modules/setup.ps1
Ignores entries in `PATH` that are invalid paths.
Fixes https://github.com/ansible-collections/ansible.windows/issues/364
setup
=> setup - Ignore invalid PATH entries for facter

changelogs/fragments/win_powershell-ets-props.yml, plugins/modules/win_powershell.ps1, tests/integration/targets/win_powershell/tasks/tests.yml
This PR will avoid serializing extended type system properties added by PowerShell. This replicates the same behaviour as `ConvertTo-Json` on newer version of PowerShell (7+). This is done for the following reasons:
* Keeps the output object type friendly, most people would expect the primitive type for these cases not a dictionary, e.g. `Get-Content` should return a list of strings not list of dicts
* The ETS prop values would also need to be sterialized to avoid the memory problems when serializing recursive property references or heavily nested values
Fixes https://github.com/ansible-collections/ansible.windows/issues/360
win_powershell
=> win_powershell - Do not serialize ETS props of primitive types

changelogs/fragments/win_updates-search-warnings.yml, plugins/modules/win_updates.ps1
If the search result returned `SuceededWithErrors` then to continue the update task. It also attempts to try and log any warnings in the search result warnings in the log for further debugging.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/366
win_updates
=> win_updates - Try to recover from search suceeded with errors

changelogs/fragments/win_command-cmd-argv.yaml, plugins/modules/win_command.ps1, plugins/modules/win_command.py, tests/integration/targets/win_command/tasks/main.yml
Adds the ability to specify a cmd using the `cmd` or `argv` module option rather than the free-form. This makes the module act more like the standard module options in Ansible rather than the `args` setup that is currently required if other module options are specified.
The module also now uses the newer `Ansible.Basic.cs` module setup to provide better invocation information with higher verbosity and more uniform parameter handling.
win_command
=> win_command - Added cmd and argv options

changelogs/fragments/win_stat-get-size.yml, plugins/modules/win_stat.ps1, plugins/modules/win_stat.py, tests/integration/targets/win_stat/tasks/tests.yml
Adds the `get_size` option to `win_stat` to control whether the size will be calculated or not. Defaults to `true` to preserve existing behaviour.
Fixes https://github.com/ansible-collections/ansible.windows/issues/384
win_stat
=> win_stat - add get_size to control size calculation

plugins/modules/win_powershell.py
Example PowerShell code in win_powershell.py has "New-Item -Path $Path -ItemType Direcotry -Force:$Force" which will throw an error
win_powershell
=> Fixed Direcotry typo in examples

changelogs/fragments/win_acl_inheritance-reg-key-sup.yml, plugins/modules/win_acl_inheritance.ps1, plugins/modules/win_acl_inheritance.py, tests/integration/targets/win_acl_inheritance/defaults/main.yml, tests/integration/targets/win_acl_inheritance/library/test_get_acl.ps1, tests/integration/targets/win_acl_inheritance/tasks/main.yml
Unfortunately, this module does not support changing the inheritance of registry keys. There are several reasons for this:
- use of the `path` type for the `path` parameter, which does not work with registry keys. (Has been replaced by `str`)
- use of `LiteralPath` parameter which does not work correctly with registry paths in Powershell 5.1 and was fixed in https://github.com/PowerShell/PowerShell/issues/11566 (was replaced by `Path`).
Changes here:
- registry path support added
- refactored from legacy to modern module style
- 'try-catch' block redesigned to handle errors of specific calls
- redesigned inheritance and explicit rules equality check
*No breaking changes. No need to rewrite playbooks*
win_acl_inheritance
=> win_acl_inheritance - added registry keys support

changelogs/fragments/win_command-PATH.yml, plugins/module_utils/Process.psm1, tests/integration/targets/module_utils_Process/library/process_pwsh_tests.ps1, tests/integration/targets/win_command/tasks/main.yml
The output of `Get-Command` shows all the results of a command if it's located more than once in the `PATH` which caused problems later on when building the exe to run. Change to code to always run with the first result found rather than the failure that happens today.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/403
win_command
=> win_command - fix exe lookup when located twice in PATH

changelogs/fragments/win_updates-write-log-arg.yml, plugins/modules/win_updates.ps1
The string needs to be formatted with `-f` and not get passed in as an array like `[string]::Format(...)`.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/411
win_updates
=> win_updates - fix incorrect API call with overloads

tests/sanity/ignore-2.14.txt
Also need to remove these ignores as sidecar support was backported to stable-2.14.
testing
=> Remove 2.14 sanity ignores

.git-blame-ignore-revs
The changes referenced in the file had some bulk sanity changes which we want to ignore from displaying in the blame. GitHub supports using this file in it's UI and it can also be used by the `git blame` CLI.
Git stuff
=> Added ignore revs file for tracking commits with bulk sanity changes

changelogs/fragments/win_acl_follow.yml, plugins/modules/win_acl.ps1, plugins/modules/win_acl.py, tests/integration/targets/win_acl/tasks/main.yml, tests/integration/targets/win_acl/tasks/tests.yml
Currently applying ACLs on a SymLink or Junction just applies the ACLs to the "link" not to the target.
There was no way to follow links, what seems to be the first intent when you set ACLs
I didn't added a new official variable for now, I let you decide if it's necessary or not.
=> Add support to apply ACL to Junctions 

changelogs/fragments/win_certificate_store-privkey-present.yml, plugins/modules/win_certificate_store.ps1, tests/integration/targets/win_certificate_store/tasks/test.yml
If you try to import a cert in the cert store wich already exists but without a private key associated, you can't because Ansible will detect no change at thumbprint level.
With that change ansible will force reimport if a private key is present during the second import.
We could imagine also force the import, if at the opposite, we remove the private key later. To be discussed.
=> Allows to force reimport a cert if you added a private key with win_certificate_store

changelogs/fragments/win_powershell-diff.yml, plugins/modules/win_powershell.ps1, plugins/modules/win_powershell.py, tests/integration/targets/win_powershell/tasks/tests.yml
Adds the `$Ansible.Diff` key which can be a dictionary like object for setting diff output as understood by Ansible. The keys of this Diff dictionary is the same as what any module would use, so keys like `before`, `after`, `prepared` will work.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/426
win_powershell
=> win_powershell - support setting diff result in script

.vscode/settings.json
Have VSCode automatically remove semicolons at the end of the line in save. This aligns with the new rules added to PSScriptAnalyzer.
vscode
=> Add vscode powershell format rule for semicolons

changelogs/fragments/win_dns_client-null-chars.yml, plugins/modules/win_dns_client.ps1, tests/integration/targets/win_dns_client/tasks/main.yml
If `Set-DnsClientServerAddress` was used to set both IPv4 and IPv6 DNS servers at the same time, the raw registry value will contain null chars. This causes problems on subsequent runs because the code will try to parse `'{ip}\0\0\0\0'` into a `IPAddress` object which fails with
```json
{
"changed": false,
"msg": "Unhandled exception while executing module: Cannot convert value \"8.8.8.8\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\" to type \"System.Net.IPAddress\". Error: \"An invalid IP address was specified.\""
}
```
The code here trims the raw value for any null chars …
=> win_dns_client - Handle null chars in raw registry dns servers value

changelogs/fragments/win_reboot-msg.yml, plugins/plugin_utils/_reboot.py
Remove some of the python 2 compatible code to clean things up and bump the connection level actions to `-vvvv`. This reduces the amount of messages shown during `-vvv` as some of the same information is displayed on the connection plugin instead and is superfluous.
win_reboot
=> win_reboot - Make the code more Python 3 like and increase display verbosity

changelogs/fragments/setup-procinfo.yml, plugins/modules/setup.ps1
On hosts with older SMBIOS versions (pre 2.5) the core and thread count fields are not present and the current code was just reading the random bytes after this type structure. This caused the processor count to be returned as random values. Instead have a fallback to the slower CIM/WMI method for older hosts.
The `ansible_processor_threads_per_core` was also being set to the number of threads per processor/CPU and not per core. This fixes the logic to return the correct value as it has been in the past.
It will also ignore any processor entries that are not populated and are not set as enabled.
Finally this also takes into account the `Core Count 2` and `Thread Count 2` fields on the SMBIOS processor information if present. This is a new field added by SMBIOS 3.0 to be able to return …
=> setup - fix processor facts for older SMBIOS versions

changelogs/fragments/win_wait_for-drained.yml, plugins/modules/win_wait_for.ps1, tests/integration/targets/win_wait_for/files/http-server.ps1, tests/integration/targets/win_wait_for/tasks/main.yml
Fixes: https://github.com/ansible-collections/ansible.windows/issues/451
win_wait_for
=> win_wait_for - fix typo found in state=drained

plugins/modules/setup.ps1
Further fixes to https://github.com/ansible-collections/ansible.windows/pull/457. Have had some reports where the SMBIOS data for the processor information exceeds 34 bytes but the SMBIOS version is still older than 2.4. This resulted in the wrong values being returned by the facts. Instead only use this data if the SMBIOS version is greater than 2.4 and the data length is long enough.
No changelog fragment needed as it's covered by what is in #457.
setup
=> setup - more fixes for core count calculation

changelogs/fragments/powershell-support-7-syntax.yml, plugins/modules/win_powershell.ps1
It is possible to use PowerShell 7 scripts with this module when `executable: pwsh.exe` is used. This means the scriptblock parser that is being used will fail in Windows PowerShell when encountering syntax added in 7. This adds a fallback to using a regex match to check if the script also contains `SupportsShouldProcess`.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/452
win_powershell
=> win_powershell - support scripts with 7 syntax

changelogs/fragments/win_package-product-id-check.yml, plugins/modules/win_package.ps1
win_package should not download/copy $path before checking the installation status if product_id is set
Based on the win_package documentation:
"When state=present, product_id is not set and the path is a URL, this file will always be downloaded to a temporary directory for idempotency checks, otherwise the file will only be downloaded if the package has not been installed based on the product_id checks."
But win_package always downloads/copies the file to a temporary location even if product_id is set and the package is installed
The productId is not being correctly checked in win_package.ps1 this commit fixes that. fixes #479 
win_package
=> win_package - fix productId check before getting remote files

.azure-pipelines/azure-pipelines.yml, tests/sanity/ignore-2.16.txt
Ansible has bumped the devel version to 2.16 and branched stable-2.15. Ensure we are still testing against 2.15 and fix up sanity ignores for the new devel version.
=> Update devel tests to track 2.16

changelogs/fragments/win_updates-rebooted.yml, plugins/action/win_updates.py, plugins/modules/win_updates.ps1, plugins/modules/win_updates.py, tests/integration/targets/win_updates/tasks/main.yml, tests/unit/plugins/action/test_win_updates.py
Add the `rebooted` return value to the `win_updates` return result to track whether the plugin had rebooted the target server or not.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/485
win_updates
=> win_updates - Add rebooted return value

changelogs/fragments/win_updates-poll-newlines.yml, plugins/action/win_updates.py, tests/unit/plugins/action/test_win_updates.py
It seems like certain connection plugins might have output with some newlines stripped. While this is a problem that should be fixed there we can certainly try and be more defensive about the output received when we read the polled information.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/477
win_updates
=> win_updates - try and improve poll output handling

changelogs/fragments/win_updates-file-locking.yml, plugins/modules/win_updates.ps1
Improve the file locking behaviour to allow the polling task to safely open a handle on the output status file. This changes the failure condition to log the failure message with a FILE_SHARE_READ handle allowing others to open a read handle to the same file at the same time.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/490
win_updates
=> win_updates - Improve file locking behaviour

changelogs/fragments/win_updates-batch-runner.yml, plugins/action/win_updates.py, plugins/module_utils/Process.cs, plugins/modules/win_updates.ps1, tests/integration/targets/module_utils_Process/library/process_cs_tests.ps1
Improve the batch runner bootstrapper that is used in win_updates to run the update code inside a batch process. This is done by starting an ephemeral process through the task scheduler that is unrelated to PowerShell and using a new API to spawn a new PowerShell process as a child of that ephemeral task. Unlike the ephemeral task process, the newly spawned process exposes the stdio handles allowing the module to have better visibility on failures and to send information to run than before.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/448
win_updates
module_utils/Process.cs
=> win_updates - Improve batch runner

changelogs/fragments/setup-bios-date.yml, plugins/modules/setup.ps1
`ParseDateString` function in `setup.ps1` is used to parse BIOS release date. Unfortunatelly, if date is not in either `MM/dd/yyyy` or `MM/dd/yy`, it will throw exception and cause the following warning:
```
[WARNING]: Error when collecting bios facts: New-Object : Exception calling ".ctor" with "0" argument(s): "String was not recognized as a valid DateTime."  At line:2 char:21  + ...         $bios = New-Object -TypeName
Ansible.Windows.Setup.SMBIOSInfo  +                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException      +
FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand      at <ScriptBlock>, <No file>: line 2
```
I found this …
=> More resilient parsing for BIOS release date

.azure-pipelines/azure-pipelines.yml, changelogs/fragments/2012-warning.yml, plugins/modules/setup.ps1, tests/integration/targets/win_dsc/aliases
Adds a warning when using the setup module for Windows OS' older than Server 2016. Server 2012 and 2012 R2 is set to become End of Life in October so this is a warning to be included in the 2.0.0 release of this collection.
This should not be merged until the 2.0.0 version of this collection is going to be released.
setup
=> Add deprecation warning for older OS'

changelogs/fragments/win_updates-output-lock.yml, plugins/action/win_updates.py, plugins/modules/win_updates.ps1
Add a retry mechanism to the output polling code to retry opening the result file if it failed due to a lock. While it is unknown what causes the lock this should at least provide a better mechanism to retry the operation in case it was another process like an antivirus that temporarily locked the file.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/490
win_updates
=> win_updates - Improve locking handling

changelogs/fragments/508-win_certificate_store-privatekey-check-update.yml, plugins/modules/win_certificate_store.ps1, tests/integration/targets/win_certificate_store/tasks/main.yml, tests/integration/targets/win_certificate_store/tasks/test.yml
This proposed change, update private key check, when exporting to pkcs12, to handle the case where the ``PrivateKey`` property is null despite it being there.
win_certificate_store
[X509Certificate2.PrivateKey](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.privatekey) is not always set, depending the method used to generate key. it's also marked as obsolete by microsoft.
A way to check this
```paste below
> New-SelfSignedCertificate -DnsName test.local
PSParentPath: Microsoft.PowerShell.Security\Certificate::LocalMachine\MY
Thumbprint                                Subject
----------                                -------
DC9D1037DCB465195F5F90400100B2759C3DF8DB  CN=test.local
> (Get-Item …
```
=> update private key check when exporting to pkcs12

changelogs/fragments/win_find-depth.yml, plugins/modules/win_find.ps1, plugins/modules/win_find.py, tests/integration/targets/win_find/tasks/main.yml, tests/integration/targets/win_find/tasks/tests.yml
Added a depth option to the win_find module to limit recursion, implementing #335 
win_find
The depth parameter is passed to the `Search-Path` function and decremented on recursive calls.
Creating an integration test for this option required adding to the existing file/folder structure and updating other tests.
=> Add depth option to win_find

changelogs/fragments/win_async-large-data-output.yml, plugins/modules/async_status.ps1, tests/integration/targets/win_async/aliases, tests/integration/targets/win_async/tasks/main.yml
Change allows JavaScriptSerializer to deserialize the largest possible JSON file. Otherwise large log files from chatty PowerShell scripts will exceed the default limit of 4MB and throw an exception.
No such limitation exists on async_status.py, so this brings the PowerShell script better in line with that
async_status.ps1
If an async tasks output exceeds 4MB (The default size limit for System.Web.Script.Serialization.JavaScriptSerializer), the deserialization will fail, throwing an exception and failing the async task.
The limit is arbitrary, and is implemented by a simple integer value that the file length is compared against. There is no practical upper limit, except for system resources.
Microsoft documentation: …
=> Remove default JSON size limitation

changelogs/fragments/win_updates-become-proc.yml, plugins/action/win_updates.py, plugins/modules/win_updates.ps1, plugins/modules/win_updates.py, tests/integration/targets/win_updates/tasks/main.yml
The task scheduler can be problematic in a few different scenarios (DA account being used, is corrupted, etc). This PR allows the user to run `win_updates` with become which will spawn the `win_updates` background task without having to use the task scheduler at all. This will give users options allowing them to choose what bootstrapping option fits better for their environment.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/543.
win_updates
=> win_updates - Add alternative to scheduled task

changelogs/fragments/setup-warning-typo.yml, plugins/modules/setup.ps1
Fix typo in the `setup` module to be `collect` and not `collection`
setup
=> Fix typo in setup module warning

changelogs/fragments/win-acl-mount-points.yml, plugins/modules/win_acl.ps1
win_acl is bronken in case of junction + follow option
win_acl
By using the option `folllow`, if the link is a junction to a volume we get an error like :
`"Volume{ad5b0320-77a0-4523-a8c8-00a52b860819}\\ file or directory does not exist on the host"`
The internal function `Get-Link` seems returns the absolute UNC path without prefix...
=> Fix broken path in case of volume junction

plugins/module_utils/CertACLHelper.cs, plugins/module_utils/_CertACLHelper.cs, plugins/modules/win_acl.ps1, plugins/modules/win_acl.py, tests/integration/targets/win_acl/defaults/main.yml, tests/integration/targets/win_acl/tasks/main.yml, tests/integration/targets/win_acl/tasks/tests.yml
I'm making this PR that essentially revives #94 to add support to `Cert:\` paths in win_acl. I tried to follow all the unresolved feedback from #94
Fixes #150 
win_acl
There is one huge caveat that I'm fairly certain my test assertions are wrong, but when I try to use `ansible-test`, I'm getting a very unhelpful error (I'll add more details in a comment), so I'm assuming that's going to block this getting merged. I realize this isn't an Ansible help forum, but if you happen to have any suggestions on what part of this stack trace is useful, I'd love to try and get these tests running
```
WARNING: Excluding target tests marked "unstable" which require --allow-unstable or prefixing with "unstable/": win_wait_for
Traceback (most recent call last):
File …
```
=> Add support for setting ACL rules on certificates

plugins/modules/win_command.py
Add the missing `stderr_lines` for `win_command` to the documentation.
For some reason this value is missing from the return values section.
win_command
https://github.com/riemers/ansible-gitlab-runner/pull/280#discussion_r1314205060
We found the doc was missing while fixing a bug in the riemers.gitlab-runner role for Windows.
**Notice stderr_lines was already present**
```paste below
ok: [srv-uitest19.zimmercas.com] => changed=false 
cmd: c:/gitlab-runner//gitlab-runner.exe --log-format json list
delta: '0:00:00.116974'
end: '2023-09-03 14:39:46.779366'
rc: 0
start: '2023-09-03 14:39:46.662391'
stderr: |-
{"arch":"amd64","level":"info","msg":"Runtime platform","os":"windows","pid":4180,"revision":"d540b510","time":"2023-09-03T10:39:46-04:00","version":"15.9.1"} …
```
=> win_command - add stderr_lines documentation

changelogs/fragments/process-creationflags.yml, plugins/module_utils/Process.cs
Fixes the typo in the enum value for CreateProtectedProcess. This should not affect any callers as creating a protected process is impossible without having a signed binary from Microsoft, it's merely done to ensure the value names are aligned properly.
Process.cs
=> Fixes ProcessCreationFlags typo

.azure-pipelines/azure-pipelines.yml, tests/sanity/ignore-2.17.txt
Bump testing to use the newly branched stable-2.16 branch and ensure devel has 2.17 ignores.
=> Start testing with Ansible 2.17/devel

changelogs/fragments/win_service_info-not-found.yml, plugins/modules/win_service_info.ps1
If a service fails to be open with `ERROR_FILE_NOT_FOUND` treat it as a warning rather than an error. This ensures it can be used to retrieve services even if some fail. It also makes it easier to debug what service it failed on for further investigation.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/556
win_service_info
=> win_service_info - ignore file not found errors

changelogs/fragments/win-share-add-cluster-support.yml, plugins/modules/win_share.ps1, plugins/modules/win_share.py, tests/integration/targets/win_share/defaults/main.yml, tests/integration/targets/win_share/tasks/main.yml, tests/integration/targets/win_share/tasks/tests.yml
This branch adds the `scope_name` param to the win_share module, allowing users to scope their file share to a Windows Server failover cluster role.
Tests have been optimized/updated accordingly - cluster specific tests have been created but are off by default. These tests require a properly configured failover cluster with one cluster role and one shared disk. I am running theses tests successfully in our internal CI pipeline.
win_share
Internal VMW Reference AWSA-32719
=> Update win_share to support cluster role shares

.azure-pipelines/azure-pipelines.yml, README.md, changelogs/fragments/ansible_support.yml, galaxy.yml, meta/runtime.yml, plugins/modules/setup.ps1, plugins/modules/win_powershell.ps1, tests/integration/targets/win_package/library/win_make_appx.ps1, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt, tests/sanity/ignore-2.17.txt
Ansible 2.14 is the oldest supported Ansible version, this PR ensures we are testing that as our minimum version.
=> Set new supported ansible minimum version to 2.14

changelogs/fragments/win_powershell-fix-using.yml, plugins/modules/win_powershell.ps1
Remove the unecessary using entry in the compiled code causing Roslyn to emit a warning during compilation. This only affected people running with an executable as the in process option did not need to recompile the code that had this.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/571
win_powershell
=> Fix win_powershell usings

changelogs/fragments/win_get_url-tls13.yml, plugins/module_utils/WebRequest.psm1
Using the win_get_url module I was getting the following error:  "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel"
However, from the machine the download was working fine within a powershell terminal. After some troubleshooting, I noticed that the issue was with TLS1.3.
Adding an extra condition for TLS1.3 actually fixed the issue. Please let me know what you think.
win_get_url
```
ansible [core 2.16.1]
config file = /ansible/ansible.cfg
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections …
```
=> Add tls13 support for win_get_url

tests/integration/targets/win_certificate_store/tasks/main.yml
The current tests fail on Server 2016 with.
```powershell
The full traceback is:
Exception calling "Import" with "3" argument(s): "The specified network password is not correct."
At line:216 char:9
+         $certs.Import($path, $password, $store_flags)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : CryptographicException
```
Looks like the version of openssl has been updated which means openssl is generating a pfx encrypted with AES256. Windows only started supporting AES256 encryption for pfx in Server 2019 so we need to generate the pfx with some extra flags on older hosts like Server 2016.
win_certificate_store
=> Use older encryption scheme for pfx tests on Server 2016

plugins/modules/win_copy.py
Adds an extra note to further clarify what needs to be done when using win_copy with a become user that is not a member of the Administrators group on the target Windows host.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/579
win_copy
=> Expand notes in win_copy and become

changelogs/fragments/PR-587-Fix-win_uri-json-depth.yaml, plugins/modules/win_uri.ps1, tests/integration/targets/win_uri/tasks/main.yml
Added depth parameter to win_uri ConvertTo-Json call
When using the win_uri module to send a json object, win_uri uses the ConvertTo-Json method. 
This method has a currently  unused parameter called Depth which represents the maximum depth of nested children to parse.
(https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-json?view=powershell-7.4#-depth)
This parameter's default value is 2, so the method does not correctly convert json objects with a higher depth.
I set it to a default of 20 which should be enough for most cases, or at least more useful than the default of 2.
win_uri.ps1
To reproduce the bug : send a json object with more than 2 levels of nesting using win_uri. The method will seem to work but the sent object …
=> Added depth parameter to win_uri ConvertTo-Json call

plugins/modules/async_status.ps1, plugins/modules/async_status.yml, tests/integration/targets/async_status/aliases, tests/integration/targets/async_status/tasks/main.yml
Add support for running async_status in check mode. This reflects recent changes in Ansible devel that enabled this on the engine side.
Support was added with the PR https://github.com/ansible/ansible/pull/82901.
ansible.windows.async_status
=> async_status - add check mode support

changelogs/fragments/win_setup-fact.yml, plugins/modules/setup.ps1, tests/integration/targets/win_setup/tasks/main.yml
Adds `ansible_win_rm_certificate_thumbprint` to the facts collected as part of the WinRM facts.
- ansible.windows
Seeing as we're already collecting this data, it would be handy to expose it as a fact for use later (for certificate renewals/updates). Would there be any objections to adding it to the facts like I have implemented below?
```
PLAY [Test playbook] **********************************************************************************************************************************************************************************************************************************************
TASK [Gathering Facts] ******************************************************************************************************************************************************** …
```
=> Add ansible_win_rm_certificate_thumbprint to facts

changelogs/fragments/win_user-account-expires.yml, plugins/modules/win_user.ps1, plugins/modules/win_user.py, tests/integration/targets/win_user/tasks/tests.yml
Added account_expires option to win_user that allows the caller to set an expiration date of a local user account.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/610
win_user
=> win_user - Added account_expires

changelogs/fragments/setup-smbios.yml, plugins/modules/setup.ps1
Provide a fallback when gathering the SMBIOS facts fails. The fallback uses the original code that retrieved the values from CIM. While this is slower it should only happen in case the SMBIOS call fails for whatever reason.
ansible.windows.setup
=> setup - Provider SMBIOS fact fallback

changelogs/fragments/win_powershell-securestring.yml, plugins/modules/win_powershell.ps1, plugins/modules/win_powershell.py, tests/integration/targets/win_powershell/tasks/failure.yml, tests/integration/targets/win_powershell/tasks/main.yml, tests/integration/targets/win_powershell/tasks/tests.yml
Added parameters_secure_string to the win_powershell module that allows users to provide a SecureString or PSCredential object that is set with no_log.
ansible.windows.win_powershell
=> win_powershell - add secure parameters

.azure-pipelines/azure-pipelines.yml, README.md, changelogs/fragments/ansible-version.yml, galaxy.yml, meta/runtime.yml, tests/sanity/ignore-2.14.txt
Ansible 2.14 is EOL so the new minimum is 2.15.
=> Raise minimum supported Ansible version to 2.15

plugins/modules/setup.yml
There's an error where the windows.setup module docs reference ansible.builtin instead of ansible.windows
Fixes #624 
ansible.windows.setup
=> Update setup.yml docs to reference proper FQCN

plugins/modules/slurp.yml
Fixes incorrect FQCN in the examples for the overloaded module slurp
Fixes #626 
ansible.windows.slurp
```paste below
```
=> Update slurp.yml to reference ansible.windows FQCN

changelogs/fragments/636-preserve-update-script-encoding.yml, plugins/modules/win_updates.ps1
We run Windows updates on some machines with more "unusual" encodings such as Chinese machines.
At some point between Ansible 7.5.0 and 8.3.0, we started encountering encoding related issues (see below).
This change base64 encode/decodes the update script wrapper and contents to prevent this.
win_updates
Example error on a Chinese machine:
```
FAILED - RETRYING: [win2019_x64_std_zh_tw]: Check for updates (3 retries left).Result was: {
"attempts": 1,
"changed": false,
"failed_update_count": 0,
"filtered_updates": {},
"found_update_count": 0,
"installed_update_count": 0,
"invocation": {
"module_args": {
"accept_list": null,
"category_names": [
...
],
"log_path": "c:\\windows_updates_pre.txt",
"reboot": false,
"reboot_timeout": 1200,
"reject_list": [
...
], …
```
=> Ensure that the encoding of the win_updates scripts is not corrupted.

changelogs/fragments/645-win_powershell-executable-timeout.yml, plugins/modules/win_powershell.ps1
The 5s timeout seems too short. It has been witnessed that first-time startup for pwsh.exe (v7.4 at least) can take 20-30s on some platforms.
Fixes #644
win_powershell
```paste below
```
=> Increase win_powershell executable timeout

changelogs/fragments/642-win_powershell-result-depth.yml, plugins/modules/win_powershell.ps1, tests/integration/targets/win_powershell/tasks/tests.yml
Fixes the handling for a value set on `$Ansible.Result` that exceeds the remove serialization depth. This is only a problem when using a custom `executable` as the value will be serialized based on the default depth value so could be truncated.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/642
win_powershell
=> Fix win_powershell result depth

changelogs/fragments/606-setup-machine-sid.yml, plugins/modules/setup.ps1
Manually enumerates the local group membership to better handle the scenario when a SID cannot be resolved.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/606
setup
=> setup - handle invalid group entries for machine_id

changelogs/fragments/623-updates-wait-error.yml, plugins/modules/win_updates.ps1
Better handle when Wait-Process failed to find the process we wanted to wait on. When looking at the decompiled code I can see that if the process existed when Wait-Process was in the process block to get the Process object but ended before the end block ran to then wait for the process to end it will throw an exception that was not converted to an error record. This just wraps the full command in try/catch instead of -ErrorAction SilentlyContinue to handle this scenario.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/623
win_updates
=> win_updates - Handle Wait-Process failing to find process

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/win_certificate_store/tasks/test.yml, tests/integration/targets/win_dsc/tasks/main.yml, tests/integration/targets/win_dsc/tasks/tests.yml, tests/integration/targets/win_owner/tasks/tests.yml, tests/integration/targets/win_package/tasks/msix_tests.yml, tests/integration/targets/win_path/tasks/main.yml, tests/integration/targets/win_reboot/tasks/main.yml, tests/integration/targets/win_service/tasks/tests.yml, tests/utils/shippable/windows.sh
Expands the testing matrix of the Windows connection plugins used in CI to cover all the supported connections of Windows.
testing
=> Expand connection plugins used in CI

.azure-pipelines/azure-pipelines.yml
Adds 2.18 back into the versions tests for the sanity checks now that devel has been bumped to 2.19.
=> Add 2.18 back into the Sanity versions for CI

plugins/modules/win_command.py, plugins/modules/win_shell.py
Update `win_command.py` and `win_shell.py` add `output_encoding_override` example
I'm fixing ansible output encoding issue recently. During google search and ai answers which is not accurate.
Adding some example and trying to complete manual.
- `ansible.windows.win_command` module
- `ansible.windows.win_shell` module
Some related issue
https://github.com/ansible/ansible/issues/54896
https://github.com/ansible/ansible/pull/54966
=> Update win_command and win_shell add `output_encoding_override` example

changelogs/fragments/setup-install-date.yml, plugins/modules/setup.ps1
Adds the ansible_os_install_date fact that contains the OS installation date as an ISO 8601 string value.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/663
setup
=> setup - Add ansible_os_install_date fact

.azure-pipelines/azure-pipelines.yml, changelogs/fragments/win-2025.yml, tests/integration/targets/win_acl/defaults/main.yml, tests/integration/targets/win_acl/meta/main.yml, tests/integration/targets/win_acl/tasks/main.yml, tests/integration/targets/win_package/library/prereq_setup.ps1, tests/integration/targets/win_package/tasks/main.yml, tests/integration/targets/win_reboot/meta/main.yml, tests/integration/targets/win_reboot/tasks/main.yml, tests/integration/targets/win_reboot/templates/post_reboot.ps1
Adds Windows Server 2025 to the test matrix and official support.
=> Add support for Windows Server 2025

.azure-pipelines/azure-pipelines.yml, .azure-pipelines/templates/test.yml, tests/requirements.yml
Adds the `microsoft.ad` collection as a requirement to run the tests. This is needed for incoming modules who need modules to manage a domain.
Testing
=> Add microsoft.ad as a test requirement

plugins/modules/win_dns_zone.ps1, plugins/modules/win_dns_zone.py, tests/integration/targets/win_dns_zone/aliases, tests/integration/targets/win_dns_zone/defaults/main.yml, tests/integration/targets/win_dns_zone/tasks/activedirectory.yml, tests/integration/targets/win_dns_zone/tasks/main.yml, tests/integration/targets/win_dns_zone/tasks/standalone.yml
Updating tasks to use modules that migrated to Windows.ad repo.
Updating tasks to use modules that migrated to Windows.ad repo.
Verifying modules on Windows Server 2019 and Windows Server 2022
win_dns_zone.ps1
win_dns_zone.py
win_dns_zone/aliases
win_dns_zone/defaults/main.yml
win_dns_zone/tasks/activedirectory.yml
win_dns_zone/tasks/main.yml
win_dns_zone/tasks/standalone.yml
Migrating Win_dns_zone from community to ansible.windows
```
=> Promote wins_dns_zone Module from community

plugins/modules/win_dhcp_lease.ps1, plugins/modules/win_dhcp_lease.py, tests/integration/targets/win_dhcp_lease/aliases, tests/integration/targets/win_dhcp_lease/defaults/main.yml, tests/integration/targets/win_dhcp_lease/tasks/main.yml, tests/integration/targets/win_dhcp_lease/tasks/tests.yml, tests/integration/targets/win_dhcp_lease/tasks/tests_checkmode.yml
- Migrated win_dhcp_lease module from ansible.community to ansible.windows
- Bug fixed - when creating a reservation from scratch, reservation name is not being applied. In addition lease was being created and then converted to reservation which is insufficient. 
- Extra tests added: 
1) Validating failure when wrong formatted mac inputted.
2) Validating failure when IP that is out of scope is inputted.
3) Validate the creation and name update of a reservation from scratch.
- Added extra example to documentation to cover the update scenario of a lease.
win_dhcp_lease
```paste below
```
=> Migrate win_dhcp_lease module to ansible.windows repo from ansible.community repo

plugins/modules/win_hosts.ps1, plugins/modules/win_hosts.py, tests/integration/targets/win_hosts/aliases, tests/integration/targets/win_hosts/defaults/main.yml, tests/integration/targets/win_hosts/meta/main.yml, tests/integration/targets/win_hosts/tasks/main.yml, tests/integration/targets/win_hosts/tasks/tests.yml
- Migration of win_hosts module from community repo to ansible.windows repo.
- Bug Fix: Fixed issue where not all lines were removed when removing multiple entries from the hosts file due to incorrect $idx handling.
- win_hosts
- Ansible windows module win_hosts migration
- As part of community.windows to ansible.windows migration.
=> Migrate win_hosts module to ansible.windows repo from ansible.community repo

tests/integration/targets/win_dsc/meta/main.yml, tests/integration/targets/win_dsc/tasks/main.yml, tests/integration/targets/win_dsc/tasks/tests.yml
- Fixed the following failure 
```
TASK [win_dsc : assert test DSC with all types] ********************************
fatal: [windows_server]: FAILED! => {
"assertion": "dsc_types_actual.DateTimeParam.Value == '2019-02-22T17:57:31.2311890+00:00'",
"changed": false,
"evaluated_to": false,
"msg": "Assertion failed"
}
```
Ansible couldn't compare properly DATE/TIME formats with different timezones as they are represented as strings, had to add a fix which converts those strings to Datetime.
- Adapted code to fix ansible-lint warnings and errors.
```paste below
```
=> Fix win_dsc integration tests

tests/integration/targets/win_user_right/tasks/main.yml, tests/integration/targets/win_user_right/tasks/tests.yml
- Fix win_user_right module integration test
- Fix win_user_right module ansible-lint warnings and errors 
win_user_right ansible-test windows-integration
Fix win_user_right variable extraction in ansible.builtin.assert tasks 
Fix ansible.lint static code test warnings and errors 
```
Fix the following test failures:
fatal: [windows_server]: FAILED! =>
{"msg": "The conditional check 'set_administrator_check.added[0]|upper == '{{ansible_hostname|upper}}\\{{ admin_account_name|upper }}'' failed. 
The error was: Conditional is marked as unsafe, and cannot be evaluated."}
```
=> Fix win_user_right ansible module integration test assertions

tests/integration/targets/win_group_membership/tasks/main.yml, tests/integration/targets/win_group_membership/tasks/tests.yml
Integration test fix and adapt files to pass ansible-lint warning and errors
- Fixed an issue in which integration test was failing on conditional check and it can’t be evaluated.
- Fixed errors and warning that ansible-lint was showing.
```paste below
Before My change the following error occured during the integration test run for win_group_membership integration test:
fatal: [windows_server]: FAILED! => {
"msg": "The conditional check 'add_another_user_to_group_again.members == [\"{{ ansible_hostname }}\\\\{{ admin_account_name }}\", \"{{ ansible_hostname }}\\\\{{ win_local_user }}\", \"NT AUTHORITY\\\\SYSTEM\", \"NT AUTHORITY\\\\NETWORK SERVICE\"]' failed. The error was: Conditional is marked as unsafe, and cannot be evaluated."
}
```
=> Fix win_group_membership integration tests

plugins/modules/win_timezone.ps1, plugins/modules/win_timezone.py, tests/integration/targets/win_timezone/aliases, tests/integration/targets/win_timezone/tasks/main.yml, tests/integration/targets/win_timezone/tasks/tests.yml
- Promote the win_timezone Module from community with git history
- plugins/modules/win_timezone.ps1
- plugins/modules/win_timezone.py
- tests/integration/targets/win_timezone/aliases
- tests/integration/targets/win_timezone/tasks/main.yml
- tests/integration/targets/win_timezone/tasks/tests.yml
- Migrating all history commits related to files/folders of win_timezone module
=> Migrate win_timezone module to ansible.windows repo from ansible.community repo

plugins/modules/win_eventlog.ps1, plugins/modules/win_eventlog.py, tests/integration/targets/win_eventlog/aliases, tests/integration/targets/win_eventlog/tasks/main.yml, tests/integration/targets/win_eventlog/tasks/tests.yml
Updating examples in the documentation file.
Verifying modules and tests.
Seealso points to community.
plugins/modules/win_eventlog.ps1
plugins/modules/win_eventlog.py
tests/integration/targets/win_eventlog/aliases
tests/integration/targets/win_eventlog/tasks/main.yml
tests/integration/targets/win_eventlog/tasks/tests.yml
Promote the win_eventlog Module from community
=> Promote the win_eventlog Module from community

tests/integration/targets/win_timezone/tasks/main.yml, tests/integration/targets/win_timezone/tasks/tests.yml
Fixes the `win_timezone` test to actually restore the original timezone.
- Test Pull Request
=> win_timezone - ensure original timezone is restored at end of test

plugins/modules/win_hotfix.ps1, plugins/modules/win_hotfix.py, tests/integration/targets/win_hotfix/aliases, tests/integration/targets/win_hotfix/defaults/main.yml, tests/integration/targets/win_hotfix/tasks/main.yml, tests/integration/targets/win_hotfix/tasks/tests.yml, tests/integration/targets/win_hotfix/tasks/tests_2012R2.yml
Promote the win_hotfix Module from community
Updating documentation examples.
plugins/modules/win_hotfix.ps1
plugins/modules/win_hotfix.py
tests/integration/targets/win_hotfix/aliases
tests/integration/targets/win_hotfix/defaults/main.yml
tests/integration/targets/win_hotfix/tasks/main.yml
tests/integration/targets/win_hotfix/tasks/tests.yml
tests/integration/targets/win_hotfix/tasks/tests_2012R2.yml
=> Promote the win_hotfix Module from community

plugins/modules/win_timezone.ps1
Upgrades the win_timzone module to the Ansible.Basic style module. This cleans up the older legacy module_util code and aligns it with the newer standards we try to write new modules in.
win_timezone
Typically I would have to create a changelog fragment for this change but as this is a new module that has not been released yet there are no public facing changes for users so it does not need one.
=> win_timezone - Upgrade to Ansible.Basic style

changelogs/fragments/win_powershell-result-array.yml, plugins/modules/win_powershell.ps1, tests/integration/targets/win_powershell/tasks/tests.yml
Fix to ensure `$Ansible.Result = @()` is returned as an empty array and not null. This was a regression on a previous fix and this change goes back to the original behaviour.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/686
win_powershell
=> win_powershell - fix empty array result value

changelogs/fragments/win_powershell-type.yml, plugins/modules/win_powershell.ps1
Some unique types may fail when calling the GetType() method. This commit adds a check to ensure the GetType() method exists before calling it to avoid an error when trying to process the output object.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/708
win_powershell
=> win_powershell - Add defensive GetType() check

plugins/modules/win_computer_description.ps1, plugins/modules/win_computer_description.py, tests/integration/targets/win_computer_description/aliases, tests/integration/targets/win_computer_description/defaults/main.yml, tests/integration/targets/win_computer_description/tasks/main.yml
The history from the community repository was preserved. The only change is in the integration test: two task names were duplicated, so they were updated to match the commands.
migrated module 'win computer description' from community to offical
=> Migrate win computer description

changelogs/fragments/717-win_get_url-checksum.yml, plugins/modules/win_get_url.ps1, plugins/modules/win_get_url.py, tests/integration/targets/win_get_url/tasks/tests_checksum.yml
Makes checksum handling behave more like ansible.builtin.get_url
Fixes #717 
win_get_url
I'm not 100% sure about the logic to trigger collecting `$dest_checksum`, it is technically called in some circumstances it wasn't before, though if I read the code right that was only in error cases since all normal exits would calculate it at the end of the script.
=> win_get_url - Make checksum work more like ansible.builtin.get_url

changelogs/fragments/win_group-basic.yml, plugins/modules/win_group.ps1
Migrates the module to use the newer Ansible.Basic framework which has better input validation, support for module/doc validation, and other benefits. This is in preparation of migrating the win_group_membership functionality into the one module.
win_group
=> win_group - Migrate to Ansible.Basic framework

meta/runtime.yml
The runtime `requires_ansible` version should include the patch/build version which is `.0`.
=> Fix up runtime ansible_requires version

changelogs/fragments/win_group-sid.yml, plugins/modules/win_group.ps1, plugins/modules/win_group.py, tests/integration/targets/win_group/tasks/main.yml, tests/integration/targets/win_group/tasks/members.yml, tests/integration/targets/win_group/tasks/tests.yml
Adds the `members` option to the `win_group` module to add/remove/set the members of a group. Also adds the `sid` return value to help uniquely identify any groups made during runtime.
win_group
=> win_group - membership and sid return value

changelogs/fragments/setup-json.yml, galaxy.yml, plugins/modules/setup.ps1
Remove the dep on ConvertFrom-AnsibleJson so that we can start to deprecate that function in Ansible exec wrapper. This is the only instance where it is used outside of the exec wrapper and it can easily be replaced by the custom PSCustomObject enumerator. Luckily this code path is not used by any of our supported connection plugins. It may be used by other connection types that cannot pipeline or through local debugging.
setup
=> setup - remove dep on shared function

changelogs/fragments/setup-vmware.yml, plugins/modules/setup.ps1
Use a wildcard matching pattern for VMWare platforms to better handle different versions in the BIOS model value.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/753
setup
=> setup - Add better VMWare detection

changelogs/fragments/win_package-checksum.yml, plugins/modules/win_package.ps1, plugins/modules/win_package.py, tests/integration/targets/win_package/tasks/failure_tests.yml, tests/integration/targets/win_package/tasks/msi_tests.yml
Note that this is only performed when installation is performed as file download does not occur in check mode, so URL sources cannot be verified in check mode anyways.
Fixes: #596
`win_package`
=> win_package: checksum verify the package before installation

changelogs/fragments/win_package-local-file-check.yml, plugins/modules/win_package.ps1, tests/integration/targets/win_package/tasks/msi_tests.yml
When the file is not downloaded by the module, it fails if the input does not exist. However, it may be populated by a `win_get_url` action which also does nothing with `--check`. Skip the assertion in this case.
win_package
=> win_package: support `--check`

changelogs/fragments/powershell-wmi-result.yml, plugins/modules/win_powershell.ps1, tests/integration/targets/win_powershell/tasks/tests.yml
Fixes the conversion of WMI output objects as they use a custom type accelerator that fails to enumerate members through the `PSObject` members.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/767
win_powershell
=> win_powershell - Fix WMI output object conversion

.azure-pipelines/commands/lint.sh, .gitignore
Update the ansible-lint version to the current one used in Galaxy/AH.
=> Update ansible-lint to current Galaxy version

.azure-pipelines/azure-pipelines.yml, README.md, changelogs/fragments/ansible-ver.yml, meta/runtime.yml
Raises the minimum Ansible version supported to 2.16 to align with the currently supported versions.
=> Raise minimum Ansible version to 2.16

changelogs/fragments/win_package.yml, plugins/modules/win_package.ps1, plugins/modules/win_package.py, tests/integration/targets/win_package/tasks/failure_tests.yml
* When path is specified as an URL with state as absent,
it is difficult to derive product id, which is required for
uninstalling the package.
Gracefully fail and let user know about this requirement.
Fixes: #667
Signed-off-by: Abhijeet Kasurde <Akasurde@redhat.com>
=> win_package: Fail uninstall when no product id is provided

changelogs/fragments/setup-product_uuid.yml, plugins/modules/setup.ps1
Adds the ansible_product_uuid fact which retrieves the DMI System Information UUID value of the host. This aligns with the behaviour of the Python setup fact gathering module.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/789
=> setup - Add ansible_product_uuid fact

.azure-pipelines/commands/entry-point.sh, .gitignore, changelogs/fragments/wdac.yml, changelogs/fragments/win_powershell-path.yml, plugins/action/win_powershell.py, plugins/modules/win_powershell.ps1, plugins/modules/win_powershell.py, plugins/modules/win_shell.ps1, tests/integration/targets/app_control/aliases, tests/integration/targets/app_control/files/New-AnsiblePowerShellSignature.ps1, tests/integration/targets/app_control/files/test-script.ps1, tests/integration/targets/app_control/handlers/main.yml, tests/integration/targets/app_control/meta/main.yml, tests/integration/targets/app_control/tasks/main.yml, tests/integration/targets/app_control/tasks/setup.yml, tests/integration/targets/app_control/tasks/test.yml, tests/integration/targets/win_powershell/files/test-script.ps1, tests/integration/targets/win_powershell/tasks/failure.yml, tests/integration/targets/win_powershell/tasks/main.yml, tests/integration/targets/win_powershell/tasks/tests.yml
Adds support for running modules like win_powershell in Windows Defender Application Control (WDAC). WDAC support requires Ansible 2.19 and the changes to the exec runner introduced there to run the modules in that environment.
=> Add support for Defender App Control

changelogs/fragments/win_service_check_flag.yml, changelogs/fragments/win_template_preserve_ansible_managed.yml, plugins/modules/win_service.ps1, tests/integration/targets/win_service/tasks/tests.yml
The `win_service` module will crash if you run it with the --check flag.
This pull request fixes the issue.
win_service
n/a
=> fix: win_service with --check flag

changelogs/fragments/copy_fix.yml, plugins/action/win_copy.py, tests/unit/plugins/action/test_win_copy.py
* symlinks should return list of dict containing src and dest
Signed-off-by: Abhijeet Kasurde <Akasurde@redhat.com>
plugins/action/win_copy.py
tests/unit/plugins/action/test_win_copy.py
=> win_copy: fix symlink information

plugins/modules/win_tempfile.py
- Uses the ansible.windows.win_tempfile module to create a temporary file with a custom prefix. 
ansible.windows.win_tempfile:
This task allows users to specify the prefix parameter to prepend a custom string to the generated temporary file. This can be useful for log aggregation, debugging, or identifying files related to specific processes.
```yaml
- name: Create temporary file with custom prefix
ansible.windows.win_tempfile:
state: file
prefix: customlog_
```
```
Before: Default temp file name begins with "ansible."
After: Temp file name begins with "customlog_"
```
=> Add support for creating temporary file with custom prefix

plugins/modules/win_copy.py
By setting `force` to `false`, the task ensures that the file is only copied if it does not already exist on the remote host
ansible.windows.win_copy
=> Add task to copy file only if it does not exist using win_copy with force: false

plugins/modules/win_reboot.py
`ansible.windows.win_reboot` module that demonstrates how to apply the `connect_timeout` parameter. This helps users manage reboots more reliably in environments with unstable or high-latency connections by increasing the connection timeout to 10 seconds.
`ansible.windows.win_reboot` module
=> ansible.windows.win_reboot: Reboot with custom connect timeout for unreliable networks

plugins/modules/win_eventlog.py
Added a playbook that demonstrates how to set the `retention_days` parameter using the `ansible.windows.win_eventlog` module.  
`ansible.windows.win_eventlog`
=> Add playbook to set retention_days for Windows event log

plugins/modules/win_template.py
- Added a playbook using the `ansible.windows.win_template` module that demonstrates setting `trim_blocks: true`.  
- This configuration removes unnecessary newlines from Jinja2 block statements, producing cleaner and more compact output files.
`ansible.windows.win_template`
=> Add playbook to render template with trim_blocks enabled for cleaner output

plugins/modules/setup.yml
`ansible.windows.setup` module that demonstrates the use of the `fact_path` parameter which showcases how to retrieve PowerShell or JSON-based facts from `C:\CustomFacts`.
`ansible.windows.setup` module
This update addresses a gap in the documentation by showing how to use `fact_path`, which was previously undocumented in the examples section. This is particularly helpful for users managing their own local facts for automation use cases.
```yaml
- name: Gather Windows facts including custom local facts from C:\CustomFacts
ansible.windows.setup:
fact_path: 'C:\\CustomFacts'
```
=> Using fact_path in ansible.windows.setup module

changelogs/fragments/win_powershell-async-output.yml, plugins/modules/win_powershell.ps1
Fix async support in Ansible 2.19 by ensuring the `win_powershell` module does not emit more than just the module result json.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/828
win_powershell
=> win_powershell - Fix async support
