ansible-collections/ansible.windows

changelogs/fragments/win_share-Allow-Root-Drives.yml
plugins/modules/win_share.ps1
tests/integration/targets/win_share/tasks/tests.yml

_From @ShachafGoldstein on Mar 01, 2020 03:30_
Fixes https://github.com/ansible-collections/ansible.windows/issues/10
win_share.ps1
Included a test
_Copied from original issue: ansible/ansible#67890_

win_share - add support for root letter shares

---

plugins/modules/async_status.ps1
plugins/modules/win_acl_inheritance.ps1
plugins/modules/win_copy.ps1
plugins/modules/win_dns_client.ps1
plugins/modules/win_domain.ps1
plugins/modules/win_domain_controller.ps1
plugins/modules/win_domain_membership.ps1
plugins/modules/win_dsc.ps1
plugins/modules/win_feature.ps1
plugins/modules/win_find.py
plugins/modules/win_optional_feature.ps1
plugins/modules/win_optional_feature.py
plugins/modules/win_regedit.ps1
plugins/modules/win_share.ps1
plugins/modules/win_shell.ps1
plugins/modules/win_updates.ps1
plugins/modules/win_wait_for.ps1
tests/integration/targets/win_reboot/templates/post_reboot.ps1
tests/integration/targets/win_stat/library/test_symlink_file.ps1
tests/integration/targets/win_user_right/library/test_get_right.ps1
tests/sanity/ignore-2.10.txt

There were a whole bunch of sanity ignores that were either trivial to fix or we never documented why we are keeping them.
many

Whole bunch of trivial sanity fixes

---

README.md

Added some info on how to manually run the doc generator.
README.md

Added info on how to generate doc pages

---

galaxy.yml
plugins/modules/win_get_url.ps1
plugins/modules/win_package.ps1
plugins/modules/win_uri.ps1
tests/integration/targets/win_reg_stat/tasks/tests.yml

Bump the beta release version for downstream testing.
collection

bump beta for downstream testing

---

plugins/modules/win_domain_controller.py

Our enterprise uses the Install From Media option to promote our domain controllers. This saves time in an otherwise lengthy process. I am adding the information used by the IFM parameters to this and the powershell script.
```paste below
```

Added Install From Media options

---

.gitignore
README.md
changelogs/config.yaml
galaxy.yml
tests/sanity/ignore-2.11.txt

Added the [antsibull-changelog](https://pypi.org/project/antsibull-changelog/) config for generating changelogs on release. Once in, the migrated fragments will need to be moved across.
changelog

Added antsibull-changelog config

---

shippable.yml
tests/sanity/ignore-2.10.txt
tests/utils/shippable/check_matrix.py
tests/utils/shippable/shippable.sh
tests/utils/shippable/units.sh

This PR makes sure we run the sanity and unit tests across multiple Ansible versions in CI.
CI

Run sanity and units tests on multiple ansible versions

---

changelogs/fragments/57804-win_acl-no-longer-needs-SeSecurityPrivilege.yml
changelogs/fragments/58466-FIX_win_find-Bug-Get-FileStat_fails_on_large_files.yml
changelogs/fragments/66451-win_dns_client-dhcp-support.yml
changelogs/fragments/reboot-add-last-boot-time-parameter.yaml
changelogs/fragments/server2008-dep.yaml
changelogs/fragments/setup.ps1-parity-with-linux-regarding-missing-local-facts-path.yml
changelogs/fragments/win_command-encoding.yaml
changelogs/fragments/win_dns_client-ipenabled.yaml
changelogs/fragments/win_dns_client_ipv6.yaml
changelogs/fragments/win_domain_controller-log.yaml
changelogs/fragments/win_find-fix-ignore-of-deduped-files.yml
changelogs/fragments/win_find-performance.yaml
changelogs/fragments/win_get_url-redirection.yaml
changelogs/fragments/win_package-basic.yaml
changelogs/fragments/win_package-revamp.yaml
changelogs/fragments/win_setup-install-type.yaml
changelogs/fragments/win_share-Implement-append-paramtere-for-access-rules.yml

Added the changelog fragments from ansible/ansible for changes that were made before the migration occurred.
many

Added migrated changelog fragments from ansible

---

README.md

Last PR had issues so  pulled latest master and trying again. Leaving it as bullet lists since that's what the most recent master has.  Also, local markdown preview of autonumbering doesn't match github view  and I worry what will be in AH vs Galaxy on that same view.. so... bullets work :-)
docs
```paste below
```

Update readme for contributor link (new pr)

---

README.md
docs/ansible.windows.win_command_module.rst
docs/ansible.windows.win_copy_module.rst
docs/ansible.windows.win_shell_module.rst
galaxy.yml
plugins/modules/win_command.py
plugins/modules/win_copy.py
plugins/modules/win_shell.py

This changes the references to the master branch to main in preparation for the branch rename.

Fix references to the master branch

---

changelogs/fragments/win_user_right.yml
plugins/modules/win_user_right.ps1
plugins/modules/win_user_right.py
tests/integration/targets/win_user_right/tasks/main.yml
tests/integration/targets/win_user_right/tasks/tests.yml

This PR refactors `win_user_right` to use the newer Ansible.Basic module framework and improve the error messages that it reports on a failure. It also adds a few more test cases for those edge scenarios.
Fixes https://github.com/ansible-collections/ansible.windows/issues/86
win_user_right

win_user_right - refactor

---

changelogs/fragments/win_hostname-basic.yml
plugins/modules/win_hostname.ps1

Add diff mode output for win_hostname and use new Ansible.Basic module wrapper.
win_hostname

win_hostname - Basic and diff support

---

galaxy.yml

Small typo

---

shippable.yml
tests/utils/shippable/shippable.sh

Change to make the shippable config like other Ansible collections.
ansible-test

Conform shippable to standard in community.general

---

changelogs/fragments/123-date_time_facts_add_epoch_int.yml
plugins/modules/setup.ps1

Fixes https://github.com/ansible/ansible/issues/72479
setup

Add epoch_int to setup

---

.azure-pipelines/azure-pipelines.yml
.azure-pipelines/scripts/aggregate-coverage.sh
.azure-pipelines/scripts/combine-coverage.py
.azure-pipelines/scripts/process-results.sh
.azure-pipelines/scripts/publish-codecov.sh
.azure-pipelines/scripts/report-coverage.sh
.azure-pipelines/scripts/run-tests.sh
.azure-pipelines/scripts/time-command.py
.azure-pipelines/templates/coverage.yml
.azure-pipelines/templates/matrix.yml
.azure-pipelines/templates/test.yml
tests/utils/shippable/shippable.sh

Move CI to Azure Pipelines
ansible-test

Add Azure Pipeline CI

---

.azure-pipelines/azure-pipelines.yml
README.md
tests/utils/shippable/shippable.sh

Fixes for AZP

---

.azure-pipelines/azure-pipelines.yml

Updated `.azure-pipelines/azure-pipelines.yml` to use the latest Azure Pipeline Test Container Image v1.9.0.
https://github.com/ansible-collections/overview/issues/45#issuecomment-807391460
- Azure Pipeline.

Updated Azure Pipeline Test Container Image URL to use v1.9.0

---

plugins/modules/win_powershell.ps1

The `GetStdHandle` returns a handle that should not be freed by the caller. By wrapping it in a `SafeFileHandle` the garbage collector would free that handle when the object is collected causing some failure when subsequent operations try to open the original stdout handle. This was an intermittent issue that occurred mostly in CI but after these changes I cannot replicate it at all.
win_powershell

win_powershell - fix errant pointers

---

README.md
docs/ansible.windows.win_environment_module.rst

Newly generated docs with the fix for `win_environment` from https://github.com/ansible-network/collection_prep/pull/54. Also simplifies the install step for the doc gen script.
win_environment

Fix win_environment doc gen and simplify doc gen install steps

---

plugins/modules/win_powershell.ps1

Hopefully the last round of fixes for this module:
* In CI the tests are hanging at a random point with no indication of what has gone wrong. I'm hoping this fixes that but I need to run this multiple times to make sure
* Using `executable` left a whole bunch of temp files due to the use of `Add-Type` and some unexplained problem in the scope it was run
* By using our `Add-CSharpType` we ensure that the proper temp dir is used which is explicitly cleaned up just in case
* When runnining something with `executable` we don't redirect the existing stdio handles so we don't have to reset them at the end
* I doubt this was an issue but I'm trying anything here
win_powershell

win_powershell - more fixes

---

.azure-pipelines/scripts/report-coverage.sh
.azure-pipelines/templates/coverage.yml
.azure-pipelines/templates/test.yml
.gitignore

Fixes up the coverage stub generation logic used in ansible-test
ansible-test

Fix up coverage stub generation

---

README.md

README: replace Freenode with Libera.Chat

README: replace Freenode with Libera.Chat

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/win_dsc-locale.yml
changelogs/fragments/win_state-datetime.yml
changelogs/fragments/win_updates-batch.yml
changelogs/fragments/win_updates-kb.yml
docs/ansible.windows.win_dsc_module.rst
docs/ansible.windows.win_regedit_module.rst
galaxy.yml

Release preparation for v1.7.1.

Prepare for v1.7.1 release

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/260-description-checkmode.yml
galaxy.yml

Prepare for v1.7.2 release

---

tests/unit/mock/loader.py

This is a recent sanity failure in devel.

Fix up new devel sanity issue

---

.azure-pipelines/azure-pipelines.yml

Adds Server 2022 to testing matrix.
tests

Added Server 2022 to CI matrix

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/reboot_error_outside_block.yml
changelogs/fragments/win_updates-executionpolicy.yml
changelogs/fragments/win_user-domain.yml
galaxy.yml

Prepare for v1.7.3 release

---

.azure-pipelines/azure-pipelines.yml
tests/sanity/ignore-2.13.txt

Preparation for devel becoming 2.13.

Added 2.12 as sanity target

---

changelogs/fragments/win_copy-dst-size.yml

I couldn't push a commit to https://github.com/ansible-collections/ansible.windows/pull/296 so this PR adds it separately.
win_copy

Add changelog for last commit

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/283-win_dns_client_IPv6_DNS.yml
changelogs/fragments/290-win_user-state-query.yml
changelogs/fragments/291-win_updates-illegal-pipe-path.yml
changelogs/fragments/add-type-env.yml
changelogs/fragments/win_copy-dst-size.yml
changelogs/fragments/win_updates-skip-optional.yml
docs/ansible.windows.win_feature_module.rst
docs/ansible.windows.win_updates_module.rst
galaxy.yml

Preparation for the v1.8.0 release

Prepare for v1.8.0 release

---

changelogs/fragments/win_dsc-write-error-standardize
changelogs/fragments/win_dsc-write-error-standardize.yml
plugins/modules/win_dsc.ps1

Centralized all the error writing logic into the new function Write-AnsibleError
win_dsc
The logic for raising an error back to ansible has been deduplicated with a new function

Error standardize

---

plugins/modules/win_find.py

Fixes https://github.com/ansible-collections/ansible.windows/issues/318
win_find

win_find - expand checksum docs

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/win_command-shell-time.yml
changelogs/fragments/win_copy-dest-calc-fix.yml
changelogs/fragments/win_dsc-composite-resource-error.yml
changelogs/fragments/win_dsc-write-error-standardize.yml
changelogs/fragments/win_powershell.yml
changelogs/fragments/win_updates-execution-policy.yml
changelogs/fragments/win_updates-return.yml
changelogs/fragments/win_updates-sleep.yml
docs/ansible.windows.win_find_module.rst
docs/ansible.windows.win_powershell_module.rst
docs/ansible.windows.win_updates_module.rst
docs/ansible.windows.win_user_right_module.rst
galaxy.yml

Preparation for v1.9.0 release.
release

Prepare for v1.9.0 release

---

.github/workflows/rst-pr.yml
docs/README.md

Same as:
- https://github.com/ansible-collections/community.windows/pull/353
Notifies authors when they edit generated documentation.
workflows

RST edit notification

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/environment_notify.yml
changelogs/fragments/setup_more_interface_data.yml
changelogs/fragments/win_reboot-pre-delay.yml
docs/ansible.windows.win_dns_client_module.rst
docs/ansible.windows.win_feature_module.rst
docs/ansible.windows.win_group_membership_module.rst
docs/ansible.windows.win_path_module.rst
docs/ansible.windows.win_reboot_module.rst
docs/ansible.windows.win_wait_for_module.rst
galaxy.yml
tests/unit/plugins/action/test_win_updates.py

Preparation for the v1.10.0 release.

Prepare for v1.10.0 release

---

.azure-pipelines/azure-pipelines.yml

Updates the test container to a new version

Update test container

---

changelogs/fragments/setup-local-facts-from-json.yml
plugins/modules/setup.ps1
tests/integration/targets/win_setup/files/json_facts.json
tests/integration/targets/win_setup/tasks/main.yml

Continuation of https://github.com/ansible-collections/ansible.windows/pull/374 that includes the changelog fragment and integration tests. I didn't have permissions to push to the original author's branch so created a new PR with their original commit.
Thanks to @Ripolin for implementing these changes.
setup

Feature json facts

---

plugins/modules/win_copy.py
plugins/modules/win_domain_controller.py
plugins/modules/win_reg_stat.py
plugins/modules/win_regedit.py

These references were pointing to the wrong collections.
docs

Fix up doc references

---

changelogs/fragments/setup-ignore-invalid-root.yml
plugins/modules/setup.ps1

Fixes: https://github.com/ansible-collections/ansible.windows/issues/397
setup

setup - fix up invalid PATH root when searching for facter

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/ansible-version-bump.yml
changelogs/fragments/setup-ignore-invalid-root.yml
changelogs/fragments/setup-invalid-PATH.yml
changelogs/fragments/setup-local-facts-from-json.yml
changelogs/fragments/win_acl_inheritance-reg-key-sup.yml
changelogs/fragments/win_command-cmd-argv.yaml
changelogs/fragments/win_package-msix-legacy.yml
changelogs/fragments/win_powershell-err-depth.yml
changelogs/fragments/win_powershell-ets-props.yml
changelogs/fragments/win_stat-get-size.yml
changelogs/fragments/win_stat-share-slash.yml
changelogs/fragments/win_updates-search-warnings.yml

Prepare for v1.11.0 release

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/win_command-PATH.yml
changelogs/fragments/win_copy-src-err.yml
galaxy.yml

Release preparation for v1.11.1.

Prepare for v1.11.1

---

README.md
galaxy.yml

Improve the documentation links as mentioned in https://github.com/ansible-collections/ansible.windows/issues/412.
Fixes: https://github.com/ansible-collections/ansible.windows/issues/412

Improve documentation links

---

plugins/modules/win_user_right.py

Update reference url of the list of available User Rights
Update hyperlink in module documentation

update docs win_user_right.py

---

plugins/filter/quote.yml
plugins/modules/async_status.yml
plugins/modules/setup.yml
plugins/modules/slurp.yml
tests/sanity/ignore-2.15.txt

Sidecar support for modules has been added to validate-modules in devel. This removes the ignore and fixes the problems in there.
testing

Fixes for new sanity checks in devel

---

tests/integration/targets/win_acl_inheritance/defaults/main.yml
tests/integration/targets/win_acl_inheritance/tasks/main.yml

Continuation of https://github.com/ansible-collections/ansible.windows/pull/410 by adding tests for UNC paths.
win_acl_inheritance

win_acl_inheritance - add tests for UNC paths

---

changelogs/fragments/win_uri-checksum.yml
plugins/modules/slurp.ps1
plugins/modules/win_domain.ps1
plugins/modules/win_environment.ps1
plugins/modules/win_path.ps1
plugins/modules/win_uri.ps1
tests/integration/targets/win_user/files/lockout_user.ps1

Fixes sanity issues based on the recent update in devel. The `win_uri` changes require a change as it changes internal functionality.
many

Fix sanity issues

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/437-win_setup-missing-false-facts.yml
changelogs/fragments/win_acl_follow.yml
changelogs/fragments/win_acl_inheritance-path-qualifier-unc-compatibility.yml
changelogs/fragments/win_certificate_store-privkey-present.yml
changelogs/fragments/win_powershell-diff.yml
changelogs/fragments/win_updates-tmp-profile.yml
changelogs/fragments/win_updates-write-log-arg.yml
changelogs/fragments/win_uri-checksum.yml
galaxy.yml

Release preparation for v1.12.0.

Prepare for v1.12.0 release

---

plugins/modules/win_powershell.py

I could not find these useful information in other places ;-)
+label: docsite_pr
It's quite self-explaining ....

Clarify host_out and output differences

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/ansible-ver.yml
changelogs/fragments/powershell-support-7-syntax.yml
changelogs/fragments/setup-procinfo.yml
changelogs/fragments/win_dns_client-null-chars.yml
changelogs/fragments/win_reboot-msg.yml
changelogs/fragments/win_wait_for-drained.yml

Prepare for v1.13.0 release

---

meta/runtime.yml

This was missed in the bump of supported versions

Bump runtime.yml to match actual supported versions

---

plugins/modules/win_updates.py

Fixes https://github.com/PowerShell/PowerShell/issues/18909
win_updates

win_updates - fix up typo in option namme example

---

plugins/modules/win_package.py

Two examples added to win_package to provide better examples for end users which doesn't read and understand the docs so well (like me).
win_package
Added couple examples which were asked (multiple) times in Reddit and Stack Overflow.
- MSSQL installation to provide example for DPAPI
- Application example how to handle multiple properties for installer
```

win_package more examples for different scenarios

---

plugins/action/win_template.py
tests/unit/plugins/action/test_win_updates.py

Fixes up newly detected sanity issues.

Fix up sanity problems

---

plugins/modules/win_acl_inheritance.py

Fixes some new sanity issues discovered in devel.
win_acl_inheritance

Fix new sanity issues

---

plugins/modules/win_certificate_store.py
plugins/modules/win_copy.py
plugins/modules/win_domain_controller.py
plugins/modules/win_domain_membership.py
plugins/modules/win_feature.py
plugins/modules/win_find.py
plugins/modules/win_get_url.py
plugins/modules/win_owner.py
plugins/modules/win_package.py
plugins/modules/win_regedit.py
plugins/modules/win_service.py
plugins/modules/win_share.py
plugins/modules/win_stat.py
plugins/modules/win_template.py
plugins/modules/win_updates.py
plugins/modules/win_user.py

change yes/no boolean to true/false

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/setup-bios-date.yml
changelogs/fragments/win_package-product-id-check.yml
changelogs/fragments/win_updates-batch-runner.yml
changelogs/fragments/win_updates-file-locking.yml
changelogs/fragments/win_updates-poll-newlines.yml
changelogs/fragments/win_updates-rebooted.yml
galaxy.yml

Preparation for the v1.14.0 release.

Prepare for v1.14.0 release

---

changelogs/fragments/dotnet-preparation.yml
plugins/module_utils/Process.cs
plugins/module_utils/SCManager.cs
plugins/modules/setup.ps1
plugins/modules/win_package.ps1
tests/integration/targets/setup_win_device/library/win_device.ps1

Fixes: https://github.com/ansible-collections/ansible.windows/issues/537

Remove some code that is incompatible with dotnet 5+

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/dotnet-preparation.yml
changelogs/fragments/win_async-large-data-output.yml
changelogs/fragments/win_group_membership-check_mode_results.yml
changelogs/fragments/win_updates-become-proc.yml
changelogs/fragments/win_updates-loop.yml
galaxy.yml

Preparations for the v2.1.0 release.

Prepare for v2.1.0 release

---

changelogs/fragments/win_updates-typo.yml
plugins/action/win_updates.py

Fixes up typo in message
Fixes: https://github.com/ansible-collections/ansible.windows/issues/554
win_updates

win_updates - fix up download typo

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/ansible_support.yml
changelogs/fragments/process-creationflags.yml
changelogs/fragments/setup-warning-typo.yml
changelogs/fragments/win-acl-mount-points.yml
changelogs/fragments/win-share-add-cluster-support.yml
changelogs/fragments/win_service_info-not-found.yml
changelogs/fragments/win_updates-typo.yml

Preparation for the v2.2.0 release.

Prepare for v2.2.0 release

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/PR-587-Fix-win_uri-json-depth.yaml
changelogs/fragments/win_get_url-tls13.yml
changelogs/fragments/win_powershell-fix-using.yml
galaxy.yml

Preparations for the v2.3.0 release.

Prepare for v2.3.0 release

---

.azure-pipelines/azure-pipelines.yml
galaxy.yml
tests/sanity/ignore-2.18.txt

Devel has been bumped to 2.18 so this aligns with the new version there.

Bump devel version to 2.18 and add 2.17 sanity

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/setup-smbios.yml
changelogs/fragments/win_powershell-securestring.yml
changelogs/fragments/win_setup-fact.yml
changelogs/fragments/win_user-account-expires.yml

Release preparation for v2.4.0 release.

Prepare for v2.4.0 release

---

.azure-pipelines/azure-pipelines.yml

Updates the test container to the latest version.
https://github.com/ansible-collections/news-for-maintainers/issues/71

Update AZP test container version

---

README.md

Minor doc update from https://github.com/ansible-collections/ansible.windows/pull/639

Update README tags for Windows

---

plugins/action/win_copy.py
tests/integration/targets/win_acl_inheritance/tasks/main.yml

New devel tests and behaviour changes need some tweaks to fix these tests.

Fix up CI failures based on new devel behaviour

---

.azure-pipelines/azure-pipelines.yml

Try to fix the CI coverage run and make it easier to rerun failed groups.
Testing

Fix CI to have coverage name and split into groups

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/0-readme.yml
changelogs/fragments/606-setup-machine-sid.yml
changelogs/fragments/623-updates-wait-error.yml
changelogs/fragments/633-owner-privileges.yml
changelogs/fragments/636-preserve-update-script-encoding.yml
changelogs/fragments/642-win_powershell-result-depth.yml
changelogs/fragments/645-win_powershell-executable-timeout.yml
changelogs/fragments/ansible-version.yml
changelogs/fragments/owner-basic.yml
changelogs/fragments/win_powershell-fix.yml

Preparations for the v2.5.0 release.
Release

Prepare for v2.5.0 release

---

README.md
docs/docsite/links.yml

If it's still super popular, feel free to close the PR.
Also we could consider removing the line whatsoever as the matrix channel doesn't seem active.
README.md

README: replace IRC with Matrix

---

plugins/modules/win_region.ps1
plugins/modules/win_region.py
plugins/modules/win_timezone.py
tests/integration/targets/win_region/aliases
tests/integration/targets/win_region/tasks/main.yml

- Promote the win_region Module from community with git history
plugins/modules/win_region.ps1
plugins/modules/win_region.py
tests/integration/targets/win_region/aliases
tests/integration/targets/win_region/tasks/main.yml
- Migrating all history commits related to files/folders of win_region module
- Add link for Windows input locale

win_region - Migrate from community

---

.azure-pipelines/azure-pipelines.yml
tests/integration/targets/win_acl/aliases
tests/integration/targets/win_acl_inheritance/aliases
tests/integration/targets/win_certificate_store/aliases
tests/integration/targets/win_dhcp_lease/aliases
tests/integration/targets/win_dns_record/aliases
tests/integration/targets/win_dns_zone/aliases

Try to rebalance the test groups and add a 4th group.
- Tests Pull Request

Rebalance CI groups - ci_complete

---

plugins/modules/win_computer_description.ps1
plugins/modules/win_computer_description.py
plugins/modules/win_mapped_drive.py
tests/integration/targets/win_computer_description/aliases
tests/integration/targets/win_computer_description/defaults/main.yml
tests/integration/targets/win_computer_description/tasks/main.yml
tests/integration/targets/win_mapped_drive/tasks/tests.yml

Updating tests with facts instead of literal path.
Update Documentation.
win_mapped_drive
Allows you to modify mapped network drives for individual users.
Also support WebDAV endpoints in the UNC form.

Migrate win mapped drive

---

plugins/modules/win_mapped_drive.ps1
plugins/modules/win_mapped_drive.py
plugins/modules/win_user_profile.py
tests/integration/targets/win_mapped_drive/tasks/main.yml
tests/integration/targets/win_mapped_drive/tasks/tests.yml

Promote the win_user_profile Module
Updating documentation
plugins/modules/win_user_profile.ps1
plugins/modules/win_user_profile.py
tests/integration/targets/win_user_profile/aliases
tests/integration/targets/win_user_profile/tasks/main.yml
tests/integration/targets/win_user_profile/tasks/tests.yml
Module and tests migration from community.windows to ansible.windows

Migrate win user profile

---

plugins/modules/win_file_compression.ps1
plugins/modules/win_file_compression.py
tests/integration/targets/win_file_compression/aliases
tests/integration/targets/win_file_compression/defaults/main.yml
tests/integration/targets/win_file_compression/meta/main.yml
tests/integration/targets/win_file_compression/tasks/main.yml

- Promote win_file_compression module from community.windows to ansible.windows
- plugins/modules/win_file_compression.ps1
- plugins/modules/win_file_compression.py
- tests/integration/targets/win_file_compression/defaults/main.yml
- tests/integration/targets/win_file_compression/meta/main.yml
- tests/integration/targets/win_file_compression/tasks/main.yml
- tests/integration/targets/win_file_compression/aliases
Module and tests migration from community.windows to ansible.windows

win_file_compression - Migrate from community 

---

plugins/modules/win_feature_info.ps1
plugins/modules/win_feature_info.py
tests/integration/targets/win_feature_info/aliases
tests/integration/targets/win_feature_info/defaults/main.yml
tests/integration/targets/win_feature_info/tasks/main.yml

Promote the win_feature_info Module from Community.windows
plugins/modules/win_feature_info.ps1
plugins/modules/win_feature_info.py
tests/integration/targets/win_feature_info/aliases
tests/integration/targets/win_feature_info/defaults/main.yml
tests/integration/targets/win_feature_info/tasks/main.yml
Promote the win_feature_info Module from Community.windows
Updating documentation
Validating tests

Migrate win feature info

---

plugins/modules/win_listen_ports_facts.ps1
plugins/modules/win_listen_ports_facts.py
tests/integration/targets/win_listen_ports_facts/aliases
tests/integration/targets/win_listen_ports_facts/tasks/main.yml

Migrate win listen ports facts module
New Module Pull Request
Win listen ports facts

Migrate win listen ports facts

---

plugins/modules/win_inet_proxy.ps1
plugins/modules/win_inet_proxy.py
tests/integration/targets/win_inet_proxy/aliases
tests/integration/targets/win_inet_proxy/library/win_inet_proxy_info.ps1
tests/integration/targets/win_inet_proxy/library/win_phonebook_entry.ps1
tests/integration/targets/win_inet_proxy/tasks/main.yml
tests/integration/targets/win_inet_proxy/tasks/tests.yml

Migrate win inet proxy
New Module Pull Request
win inet proxy module

Migrate win inet proxy

---

tests/integration/targets/win_group/defaults/main.yml
tests/integration/targets/win_group/tasks/main.yml
tests/integration/targets/win_group/tasks/tests.yml

Rewrites win_group tests to newer standard in preparation for new changes adding in future PRs.
- Tests Pull Request
win_group

Rewrite win_group tests

---

changelogs/fragments/win_group-diff.yml
plugins/modules/win_group.ps1
plugins/modules/win_group.py
tests/integration/targets/win_group/tasks/tests.yml

Added `--diff` output support for the `win_group` module and also added tests for unsetting the description using an empty string value.
win_group

win_group - Added diff support

---

plugins/modules/win_product_facts.ps1
plugins/modules/win_product_facts.py
tests/integration/targets/win_product_facts/aliases
tests/integration/targets/win_product_facts/tasks/main.yml

Migrate module `win_product_facts`
`win_product_facts`
Fixes [this](https://github.com/ansible-collections/community.windows/issues/540) issue from the community

migrate win product facts module

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/717-win_get_url-checksum.yml
changelogs/fragments/win_group-basic.yml
changelogs/fragments/win_group-diff.yml
changelogs/fragments/win_group-sid.yml
changelogs/fragments/win_group_membership-unique.yml
galaxy.yml

Release summary 2.7.0

---

codecov.yml

Allows us to ignore any entries that are unrelated to the collection and fix up some testing paths.

Create codecov settings file

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/setup-json.yml
changelogs/fragments/setup-vmware.yml
changelogs/fragments/win_package-checksum.yml
changelogs/fragments/win_package-local-file-check.yml

Prepare for v2.8.0 release

---

plugins/modules/win_get_url.py

see #773 
win_get_url
fixes #773

fix win_get_url doc example name

---

README.md

New requirements around the support statement from the certification side.

Further clarify support statement

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/ansible-ver.yml
changelogs/fragments/powershell-wmi-result.yml
changelogs/fragments/removal.yml
changelogs/fragments/win_find_case_sensitive.yml
changelogs/fragments/win_regedit-decimal.yml
changelogs/fragments/win_template.yml

Release preparation for v3.0.0.

Prepare for v3.0.0 release

---

galaxy.yml

Bumps version in preparation for upcoming changes.

Bump version after 3.0.0 release

---

changelogs/fragments/win_dns_client.yml
plugins/modules/win_dns_client.ps1
plugins/modules/win_dns_client.py
tests/integration/targets/win_dns_client/tasks/main.yml

* Added support for DNS suffixsearchlist
Fixes: #656
Signed-off-by: Abhijeet Kasurde <Akasurde@redhat.com>

win_dns_client: Add support for suffixsearchlist

---

plugins/modules/win_service.py

Be more clear that this is just for managing services.
Fixes #791 
win_service

Drop "and query" from win_service description (fixes #791)

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/785-cloudstack_kvm_to_virtual.yml
changelogs/fragments/setup-product_uuid.yml
changelogs/fragments/wdac.yml
changelogs/fragments/win_dns_client.yml
changelogs/fragments/win_package.yml
changelogs/fragments/win_powershell-path.yml

Release preparation for v3.1.0.

Prepare for v3.1.0 release

---

tests/unit/conftest.py
tests/unit/plugins/action/test_win_updates.py
tests/unit/plugins/filter/test_quote.py

Signed-off-by: Abhijeet Kasurde <Akasurde@redhat.com>
- Test Pull Request
tests/unit/conftest.py
tests/unit/plugins/action/test_win_updates.py
tests/unit/plugins/filter/test_quote.py

Remove Python 2 specific code

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/copy_fix.yml
changelogs/fragments/win_find.yml
changelogs/fragments/win_service_check_flag.yml
changelogs/fragments/win_template_preserve_ansible_managed.yml
galaxy.yml

Release preparation for v3.2.0.

Prepare for v3.2.0 release

---

plugins/action/win_template.py
plugins/plugin_utils/_quote.py

Removes some old Python 2 compatibility code that is no longer and fails some sanity checks.

Remove old Python 2 code failing sanity checks

---

changelogs/fragments/code-cleanup.yml
plugins/action/win_copy.py
plugins/action/win_reboot.py
plugins/action/win_updates.py
plugins/plugin_utils/_reboot.py
tests/unit/plugins/action/test_win_updates.py

Removes some references to the play_context attributes in favour of the new task attributes. Removes the code using the PowerShell's internal API for encoding scripts to a custom one that achieves the same outcome.

Tidy up old code
